; This is the main configuration file of the 
; Comments start with ';', as in php.ini
; Last changes 02.12.2025 by Guy Bami


[local_database_settings]
dbHost = "localhost"                ;database Host Name or IP
dbUser = "root"                     ;database User
dbUserPassword = "root4Web!"        ;database hash password
dbName =  "khev"              ;  database name


; [prod_database_settings]
[database_settings]
dbHost = "kameruner-heilbronn.de.mysql"              ;database Host Name or IP
dbUser = "kameruner_heilbronn_de"                     ;database User
dbUserPassword = "fvtK6MLh"                     ;database hash password
dbName =  "kameruner_heilbronn_de"              ;  database name

[release_version]
version = "1.0"

[deployment_requirement]
PhpVersion = "8.2+"
MySQLVersion = "8.3+"

[phmmyadmin_settings]
userName = "kameruner_heilbronn_de"
userKey = "kameruner_heilbronn_de"
Host = "kameruner-heilbronn.de.mysql"