
; This is the main configuration file of the 
; Comments start with ';', as in php.ini
; Created on 16.10.2014 by Guy Bami


[database_settings]
dbHost = "localhost"                ;database Host Name or IP
dbUser = "root"                     ;database User
dbUserPassword = "root4Web!"        ;database hash password "root4Web!"
dbName =  "khev"              ;  database name


[local_database_settings]
dbHost = "localhost"                ;database Host Name or IP
dbUser = "root"                     ;database User
dbUserPassword = "root4Web!"        ;database hash password "root4Web!"
dbName =  "khev"              ;  database name



[live_database_settings]
dbHost = "ccq9128cw.mysql.service.one.com"              ;database Host Name or IP
dbUser = "ccq9128cw_khev"                     ;database User
dbUserPassword = "root4db!"         ;database hash password
dbName =  "ccq9128cw_khev"              ;  database name

[mssql_database_settings]
dbHost = "(local)\sqlexpress"       ;database Host Name or IP; MS SQL: 
dbUser = "xcs"                      ;database User; xcs; root
dbUserPassword = "xcs"             ;database hash password  xcs
dbName =  "xls_test"               ;database name ;bprojectDB ; carug_fret; test_xls




[release_version]
version = "1.2"

[deployment_requirement]
PhpVersion = "8.2+"
MySQLVersion = "5.5+"

[ftp_connection]
Host = ssh.ccq9128cw.service.one
User = ccq9128cw_ssh
Port = 22
ftp-password = "root4ftp!"