
; This is the main configuration file of the 
; Comments start with ';', as in php.ini
; Created on 16.10.2014 by Guy Bami


[database_settings]
dbHost = "localhost"                ;database Host Name or IP
dbUser = "root"                     ;database User
dbUserPassword = ""        ;database hash password "root4Web!"
dbName =  "khev"              ;  database name



[live_database_settings]
dbHost = "bd.carug.fr"              ;database Host Name or IP
dbUser = "bami"                     ;database User
dbUserPassword = "bami2014"         ;database hash password
dbName =  "carug_fret"              ;  database name

[mssql_database_settings]
dbHost = "(local)\sqlexpress"       ;database Host Name or IP; MS SQL: 
dbUser = "xcs"                      ;database User; xcs; root
dbUserPassword = "xcs"             ;database hash password  xcs
dbName =  "xls_test"               ;database name ;bprojectDB ; carug_fret; test_xls




[release_version]
version = "1.3"

[deployment_requirement]
PhpVersion = "5.4+"
MySQLVersion = "5.5+"

[ftp_passworf]
ftp-password = "ftp4khev"