
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The EventBillSummary cotntroller entity class.
 * @author
 *    Guy Bami W.
 */
include_once 'BaseController.php';

class EventBillSummaryController extends BaseController {

    private $eventBillSummary = null;

    /**
     * Constructor of the EventBillSummary controller 
     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->eventBillSummary = new EventBillSummary();
    }

    /**
     * Gets all EventBillSummary entities
     * @return mixed object having all EventBillSummary entities
     *    or string with the Exception details if error occured
     */
    public function getAllEventBillSummaries() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->eventBillSummary->selectAllEventBillSummaries();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"billSummaryId":"' . $resultObject[$i]["billSummaryId"] . '"'
                        . ',"eventId":"' . $resultObject[$i]["eventId"] . '"'
                        . ',"title":"' . $resultObject[$i]["title"] . '"'
                        . ',"summary":"' . $resultObject[$i]["summary"] . '"'
                        . ',"summaryFileName":"' . $resultObject[$i]["summaryFileName"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new EventBillSummary entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewEventBillSummary($jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->eventBillSummary->insertNewEventBillSummary(
                $formJsonValues['eventId']
                , $formJsonValues['title']
                , $formJsonValues['summary']
                , $formJsonValues['summaryFileName']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates EventBillSummary entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateEventBillSummary($billSummaryId, $updateMode, $jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->eventBillSummary->updateEventBillSummaryDetails(
                    $billSummaryId
                    , $formJsonValues['eventId']
                    , $formJsonValues['title']
                    , $formJsonValues['summary']
                    , $formJsonValues['summaryFileName']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->eventBillSummary->updateEventBillSummaryEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteEventBillSummaries($jsonData) {

        // delete entity using model
        $resultObject = $this->eventBillSummary->deleteSelectedEventBillSummaries($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllEventBillSummaries() {

        // delete entities using corresponding model
        $resultObject = $this->eventBillSummary->deleteAllEventBillSummaries();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllEventBillSummaries();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewEventBillSummary($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $billSummaryId = $_POST['billSummaryId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateEventBillSummary($billSummaryId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteEventBillSummaries($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllEventBillSummaries();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['billSummaryId'])) {
                    $billSummaryId = $_POST['billSummaryId'];
                    $resultObject = $this->eventBillSummary->getEventBillSummaryDetails($billSummaryId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "addNewItem":
                //insert new entity
                $resultObject = Array('0' => Array(
                        eventId => ''
                        , title => ''
                        , summary => ''
                        , summaryFileName => ''
                    )
                );
                $postbackData = Utils::convertArrayToJson($resultObject[0]);
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['billSummaryId'])) {
                    $billSummaryId = $_POST['billSummaryId'];
                    $resultObject = $this->eventBillSummary->getEventBillSummaryDetails($billSummaryId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
        }
        return $postbackData;
    }

}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    $eventBillSummaryController = new EventBillSummaryController($userAction);
    $eventBillSummaryController->setUserAction($userAction);
    $postbackContent = $eventBillSummaryController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

