
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The Event cotntroller entity class.
 * @author
 *    Guy Bami
 */
include_once 'BaseController.php';

class EventController extends BaseController {

    private $event = null;

    /**
     * Constructor of the Event controller 

     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->event = new Event();
    }

    /**
     * Gets all Event entities
     * @return mixed object having all Event entities
     *    or string with the Exception details if error occured
     */
    public function getAllEvents() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->event->selectAllEvents();
        //print_r($resultObject);
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"eventId":"' . $resultObject[$i]["eventId"] . '"'
                        . ',"title":"' . $resultObject[$i]["title"] . '"'
                        . ',"category":"' . $resultObject[$i]["category"] . '"'
                        . ',"date":"' . $resultObject[$i]["date"] . '"'
                        . ',"location":"' . $resultObject[$i]["location"] . '"'
                        . ',"summary":"' . Utils::escapeJsonChars($resultObject[$i]["summary"]) . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
            
        return $entitiesList;
    }

    /**
     * Inserts new Event entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewEvent($jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->event->insertNewEvent(
                $formJsonValues['title']
                , $formJsonValues['category']
                , $formJsonValues['date']
                , $formJsonValues['location']
                , $formJsonValues['summary']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates Event entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateEvent($eventId, $updateMode, $jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->event->updateEventDetails(
                    $eventId
                    , $formJsonValues['title']
                    , $formJsonValues['category']
                    , $formJsonValues['date']
                    , $formJsonValues['location']
                    , $formJsonValues['summary']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->event->updateEventEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteEvents($jsonData) {

        // delete entity using model
        $resultObject = $this->event->deleteSelectedEvents($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllEvents() {

        // delete entities using corresponding model
        $resultObject = $this->event->deleteAllEvents();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    
    public function getAllEventsByCategory($category) {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->event->getAllEventsByCategory($category);
        //print_r($resultObject);
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
            
                $entitiesList .=
                        '{"eventId":"' . $resultObject[$i]["eventId"] . '"'
                        . ',"title":"' . $resultObject[$i]["title"] . '"'
                        . ',"category":"' . $resultObject[$i]["category"] . '"'
                        . ',"date":"' . $resultObject[$i]["date"] . '"'
                        . ',"location":"' . $resultObject[$i]["location"] . '"'
                        . ',"summary":"' . Utils::escapeJsonChars($resultObject[$i]["summary"]) . '"'
                        // foreign
                        . ',"numPhotos":"' . $resultObject[$i]["numPhotos"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
            
        return $entitiesList;
    }
    
    
    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllEvents();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewEvent($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $eventId = $_POST['eventId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateEvent($eventId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteEvents($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllEvents();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['eventId'])) {
                    $eventId = $_POST['eventId'];
                    $resultObject = $this->event->getEventDetails($eventId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "addNewItem":
                //insert new entity
                $resultObject = Array('0' => Array(
                        title => ''
                        , category => ''
                        , date => ''
                        , location => ''
                        , summary => ''
                    )
                );
                $postbackData = Utils::convertArrayToJson($resultObject[0]);
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['eventId'])) {
                    $eventId = $_POST['eventId'];
                    $resultObject = $this->event->getEventDetails($eventId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "getAllTournaments":
                $category = "Tournament";
                $postbackData = $this->getAllEventsByCategory($category);
                break;
            case "getAllChallenges":
                $category = "Challenge";
                $postbackData = $this->getAllEventsByCategory($category);
                break;
        }
        return $postbackData;
    }

}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    $eventController = new EventController($userAction);
    $eventController->setUserAction($userAction);
    $postbackContent = $eventController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

