
            <?php 


               /**
                * This module was auto generated by GWatcho-Code generator
                * The EventPhotoComment cotntroller entity class.
                * @author
                *    Guy Bami W.
                */

  
include_once 'BaseController.php';


 class EventPhotoCommentController extends BaseController { 
private $eventPhotoComment = null; 


                 /**
                  *Constructor of the EventPhotoComment controller 

                   * @param $userAction string the user action
* @param $userRoles array the user roles 
                  */
                
function __construct($userAction, $userRoles = array()){ 
     parent::__construct($userAction, $userRoles);
                        $this->eventPhotoComment = new EventPhotoComment(); }


           /**
            * Gets all EventPhotoComment entities
            * @return mixed object having all EventPhotoComment entities
            *    or string with the Exception details if error occured
            */
            public function getAllEventPhotoComments(){

                $itemSperator = ",";
                $entitiesList = "";
                $resultObject = $this->eventPhotoComment->selectAllEventPhotoComments();
                if(is_string($resultObject)){
                    return Utils::formatJsonErrorMessage($resultObject);
                }
                else if(is_array($resultObject)){
                    for ($i = 0; $i < count($resultObject); $i++)
                    {
                        $entitiesList .= 
'{"photoCommentId":"'.$resultObject[$i]["photoCommentId"].'"'
.',"photoId":"'.$resultObject[$i]["photoId"].'"'
.',"userId":"'.$resultObject[$i]["userId"].'"'
.',"commentText":"'.$resultObject[$i]["commentText"].'"'
.',"date":"'.$resultObject[$i]["date"].'"'
.'}';

                        if ($i != count($resultObject) - 1) {
                            $entitiesList .= $itemSperator;
                        }
                    }
                    // close json list
                    $entitiesList = "[" . $entitiesList . "]";

                }
                return $entitiesList;

            }


           /**
             * Inserts new EventPhotoComment entity
             * @param mixed $jsonData json object entity to insert
             * @return mixed  true if insertion was successful
             *    or string with the Exception details if error occured
             */
            public function insertNewEventPhotoComment($jsonData){

                // get json posted values from request
                $formJsonValues = json_decode($jsonData, true);
                $postbackData = "";
                $resultObject = null;
                // insert entity using model object
                $resultObject = $this->eventPhotoComment->insertNewEventPhotoComment(
                                $formJsonValues['photoId']
,$formJsonValues['userId']
,$formJsonValues['commentText']
,$formJsonValues['date']


                );

                if(is_bool($resultObject) || is_int($resultObject)){
                    $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Updates EventPhotoComment entity via POST request
             * @param int $customerId
             * @param string $updateMode
             * @param mixed $jsonData
             * @return mixed  true if update was successful
             *    or string with the Exception details if error occured
             */
            public function updateEventPhotoComment($photoCommentId, $updateMode, $jsonData){

                // get json posted values from request
                $formJsonValues = json_decode($jsonData, true);
                $postbackData = "";
                $resultObject = null;
                if ($updateMode == "allFields") {
                    // update all entity fields
                    $resultObject = $this->eventPhotoComment->updateEventPhotoCommentDetails(
                                  $photoCommentId
,$formJsonValues['photoId']
,$formJsonValues['userId']
,$formJsonValues['commentText']
,$formJsonValues['date']


                    );
                    if(is_bool($resultObject)){
                        if($resultObject == true){
                            $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                        }
                        else{
                            $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                        }
                    }
                    else if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }

                }
                else if ($updateMode == "inlineUpdate") {
                    // Update entity from the datagrid
                    $fieldName = $formJsonValues['fieldName'];
                    $keyFieldValue = $formJsonValues['entityKeyId'];
                    $newFieldValue = $formJsonValues['newFieldValue'];
                    $resultObject = $this->eventPhotoComment->updateEventPhotoCommentEntityField($fieldName, $keyFieldValue, $newFieldValue);
                    if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }
                    else if(is_bool($resultObject)){
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
                    }
                }
                return $postbackData;

            }


           /**
             * Deletes all selected entities via POST request
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteEventPhotoComments($jsonData){

                // delete entity using model
                $resultObject = $this->eventPhotoComment->deleteSelectedEventPhotoComments($jsonData);
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Deletes all entities
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteAllEventPhotoComments(){

                // delete entities using corresponding model
                $resultObject = $this->eventPhotoComment->deleteAllEventPhotoComments();
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Get dynamic page content
             * @return mixed
             */
            public function getDynamicPageContent() {

                $postbackData = "Undefined Content";
                $resultObject = null;
                switch ($this->getUserAction()) {
                    case "getAllItems":
                        $postbackData = $this->getAllEventPhotoComments();
                        break;
                    case "addNewItem":
                    case "insertNewItem":
                        $jsonData = array();
                        if (isset($_POST['formValues'])) {
                            $jsonData = $_POST['formValues'][0];
                        }
                        $postbackData = $this->insertNewEventPhotoComment($jsonData);
                        break;
                    case "updateItem":
                        $updateMode = "allFields";
                        if (isset($_POST['updateMode'])) {
                            $updateMode = $_POST['updateMode'];
                        }
                        $photoCommentId = $_POST['photoCommentId'];
                        $jsonData = $_POST['formValues'][0];
                        $postbackData = $this->updateEventPhotoComment($photoCommentId, $updateMode, $jsonData);
                        break;
                    case "deleteItem":
                        $jsonData = array();
                        if (isset($_POST['selectedIds'])) {
                            $jsonData = $_POST['selectedIds'];
                        }
                        $postbackData = $this->deleteEventPhotoComments($jsonData);
                        break;
                    case "deleteAllItems":
                        $postbackData = $this->deleteAllEventPhotoComments();
                        break;
                    case "editDetails":
                        $postbackData = "Undefined Content";
                        if ( isset($_POST['photoCommentId']) ) {
                            $photoCommentId = $_POST['photoCommentId'];
                            $resultObject = $this->eventPhotoComment->getEventPhotoCommentDetails($photoCommentId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                    case "addNewItem":
                        //insert new entity
                        $resultObject = Array('0' => Array(
                             photoId=>''
,userId=>''
,commentText=>''
,date=>''


                           )
                        );
                        $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        break;
                    case "viewDetails":
                    case "cancelChanges":
                        if ( isset($_POST['photoCommentId']) ) {
                            $photoCommentId = $_POST['photoCommentId'];
                            $resultObject = $this->eventPhotoComment->getEventPhotoCommentDetails($photoCommentId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                }
                return $postbackData;

            }

} 


            $userAction = null;
            if (isset($_POST) && isset($_POST['userAction'])) {
                $userAction = $_POST['userAction'];
            }
            if (!isset($userAction)) {
                echo "No action has been set";
            }
            else{
                $eventPhotoCommentController = new EventPhotoCommentController($userAction);
                $eventPhotoCommentController->setUserAction($userAction);
                $postbackContent = $eventPhotoCommentController->getDynamicPageContent();

                // send back content to client
                echo $postbackContent;
            }
            

