
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The EventPhoto cotntroller entity class.
 * @author
 *    Guy Bami W.
 */
include_once 'BaseController.php';

class EventPhotoController extends BaseController {

    private $eventPhoto = null;

    /**
     * Constructor of the EventPhoto controller 

     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->eventPhoto = new EventPhoto();
    }

    /**
     * Gets all EventPhoto entities
     * @return mixed object having all EventPhoto entities
     *    or string with the Exception details if error occured
     */
    public function getAllEventPhotos() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->eventPhoto->selectAllEventPhotos();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"photoId":"' . $resultObject[$i]["photoId"] . '"'
                        . ',"eventId":"' . $resultObject[$i]["eventId"] . '"'
                        . ',"fileFullName":"' . $resultObject[$i]["fileFullName"] . '"'
                        . ',"title":"' . $resultObject[$i]["title"] . '"'
                        // foreign fields
                        . ',"eventTitle":"' . $resultObject[$i]["eventTitle"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new EventPhoto entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewEventPhoto($jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->eventPhoto->insertNewEventPhoto(
                $formJsonValues['eventId']
                , $formJsonValues['fileFullName']
                , $formJsonValues['title']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates EventPhoto entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateEventPhoto($photoId, $updateMode, $jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->eventPhoto->updateEventPhotoDetails(
                    $photoId
                    , $formJsonValues['eventId']
                    , $formJsonValues['fileFullName']
                    , $formJsonValues['title']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->eventPhoto->updateEventPhotoEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteEventPhotos($jsonData) {

        // delete entity using model
        $resultObject = $this->eventPhoto->deleteSelectedEventPhotos($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllEventPhotos() {

        // delete entities using corresponding model
        $resultObject = $this->eventPhoto->deleteAllEventPhotos();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }
    
    
    public function assignPhotosToEvent($eventId, $jsonData, $title){
        $resultObject = $this->eventPhoto->assignPhotosToEvent($eventId, $jsonData, $title);
        $itemSperator = ",";
        $entitiesList = "";
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"insertedItemKey":"' . $resultObject[$i]["insertedItemKey"] . '"'
                        . ',"fileName":"' . $resultObject[$i]["fileName"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }
    
    /**
     * Gets all EventPhoto entities for the given eventId
     * @return mixed object having all EventPhoto entities
     *    or string with the Exception details if error occured
     */
    public function selectAllPhotosByEvent($eventId) {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->eventPhoto->selectAllPhotosByEvent($eventId);
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"photoId":"' . $resultObject[$i]["photoId"] . '"'
                        . ',"eventId":"' . $resultObject[$i]["eventId"] . '"'
                        . ',"fileFullName":"' . $resultObject[$i]["fileFullName"] . '"'
                        . ',"title":"' . $resultObject[$i]["title"] . '"'
                        // foreign fields
                        . ',"eventTitle":"' . $resultObject[$i]["eventTitle"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllEventPhotos();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewEventPhoto($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $photoId = $_POST['photoId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateEventPhoto($photoId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteEventPhotos($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllEventPhotos();
                break;
            case "editDetails":
                if (isset($_POST['photoId'])) {
                    $photoId = $_POST['photoId'];
                    $resultObject = $this->eventPhoto->getEventPhotoDetails($photoId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "addNewItem":
                //insert new entity
                $resultObject = Array('0' => Array(
                        eventId => ''
                        , fileFullName => ''
                        , title => ''
                    )
                );
                $postbackData = Utils::convertArrayToJson($resultObject[0]);
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['photoId'])) {
                    $photoId = $_POST['photoId'];
                    $resultObject = $this->eventPhoto->getEventPhotoDetails($photoId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "assignPhotosToEvent":
                $jsonData = array();
                if (isset($_POST['fileNamesList'])) {
                    $jsonData = $_POST['fileNamesList'];
                }
                $eventId = $_POST['eventId'];
                $title = $_POST['title'];
                $postbackData = $this->assignPhotosToEvent($eventId, $jsonData, $title);
                break;
            case "selectAllPhotosByEvent":
                $eventId = $_POST['eventId'];
                $postbackData = $this->selectAllPhotosByEvent($eventId);
                break;
        }
        return $postbackData;
    }

}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    $eventPhotoController = new EventPhotoController($userAction);
    $eventPhotoController->setUserAction($userAction);
    $postbackContent = $eventPhotoController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

