
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The Expense cotntroller entity class.
 * @author
 *    Guy Bami
 */
include_once 'BaseController.php';

class ExpenseController extends BaseController {

    private $expense = null;

    /**
     * Constructor of the Expense controller 
     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->expense = new Expense();
    }

    /**
     * Gets all Expense entities
     * @return mixed object having all Expense entities
     *    or string with the Exception details if error occured
     */
    public function getAllExpenses() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->expense->selectAllExpenses();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"expenseId":"' . $resultObject[$i]["expenseId"] . '"'
                        . ',"eventId":"' . $resultObject[$i]["eventId"] . '"'
                        . ',"title":"' . $resultObject[$i]["title"] . '"'
                        . ',"amount":"' . str_replace(".", ",", $resultObject[$i]["amount"]) . '"' // for german locale
                        . ',"category":"' . $resultObject[$i]["category"] . '"'
                        . ',"billFileName":"' . $resultObject[$i]["billFileName"] . '"'
                        . ',"transactionDate":"' . $resultObject[$i]["transactionDate"] . '"'
                        . ',"eventTitle":"' . $resultObject[$i]["eventTitle"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new Expense entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewExpense($jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->expense->insertNewExpense(
                $formJsonValues['eventId']
                , $formJsonValues['title']
                , $formJsonValues['amount']
                , $formJsonValues['category']
                , $formJsonValues['billFileName']
                , $formJsonValues['transactionDate']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates Expense entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateExpense($expenseId, $updateMode, $jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->expense->updateExpenseDetails(
                    $expenseId
                    , $formJsonValues['eventId']
                    , $formJsonValues['title']
                    , $formJsonValues['amount']
                    , $formJsonValues['category']
                    , $formJsonValues['billFileName']
                    , $formJsonValues['transactionDate']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->expense->updateExpenseEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteExpenses($jsonData) {

        // delete entity using model
        $resultObject = $this->expense->deleteSelectedExpenses($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllExpenses() {

        // delete entities using corresponding model
        $resultObject = $this->expense->deleteAllExpenses();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }
    
    public function getAllExpensesByYear() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->expense->selectAllExpensesByYear();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{' 
                        . '"currentMonth":"'.$resultObject[$i]["currentMonth"].'"'
                        . ',"sumExpenses":"'.$resultObject[$i]["sumExpenses"].'"'
                        . ',"currentYear":"'.$resultObject[$i]["currentYear"].'"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllExpenses();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewExpense($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $expenseId = $_POST['expenseId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateExpense($expenseId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteExpenses($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllExpenses();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['expenseId'])) {
                    $expenseId = $_POST['expenseId'];
                    $resultObject = $this->expense->getExpenseDetails($expenseId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "addNewItem":
                //insert new entity
                $resultObject = Array('0' => Array(
                        eventId => ''
                        , title => ''
                        , amount => ''
                        , category => ''
                        , billFileName => ''
                        , transactionDate => ''
                    )
                );
                $postbackData = Utils::convertArrayToJson($resultObject[0]);
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['expenseId'])) {
                    $expenseId = $_POST['expenseId'];
                    $resultObject = $this->expense->getExpenseDetails($expenseId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;  
            case "getAllExpensesByYear":
                $postbackData = $this->getAllExpensesByYear();
                break;
        }
        return $postbackData;
    }

}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    $expenseController = new ExpenseController($userAction);
    $expenseController->setUserAction($userAction);
    $postbackContent = $expenseController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

