
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The Income cotntroller entity class.
 * @author
 *    Guy Bami
 */
include_once 'BaseController.php';

class IncomeController extends BaseController {

    private $income = null;

    /**
     * Constructor of the Income controller 

     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->income = new Income();
    }

    /**
     * Gets all Income entities
     * @return mixed object having all Income entities
     *    or string with the Exception details if error occured
     */
    public function getAllIncomes() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->income->selectAllIncomes();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"incomeId":"' . $resultObject[$i]["incomeId"] . '"'
                        . ',"eventId":"' . $resultObject[$i]["eventId"] . '"'
                        . ',"title":"' . $resultObject[$i]["title"] . '"'
                        //. ',"amount":"' . $resultObject[$i]["amount"] . '"'
                        . ',"amount":"' . str_replace(".", ",", $resultObject[$i]["amount"]) . '"' // for german locale
                        . ',"category":"' . $resultObject[$i]["category"] . '"'
                        . ',"billFileName":"' . $resultObject[$i]["billFileName"] . '"'
                        . ',"transactionDate":"' . $resultObject[$i]["transactionDate"] . '"'
                        . ',"eventTitle":"' . $resultObject[$i]["eventTitle"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new Income entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewIncome($jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->income->insertNewIncome(
                $formJsonValues['eventId']
                , $formJsonValues['title']
                , $formJsonValues['amount']
                , $formJsonValues['category']
                , $formJsonValues['billFileName']
                , $formJsonValues['transactionDate']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates Income entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateIncome($incomeId, $updateMode, $jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->income->updateIncomeDetails(
                    $incomeId
                    , $formJsonValues['eventId']
                    , $formJsonValues['title']
                    , $formJsonValues['amount']
                    , $formJsonValues['category']
                    , $formJsonValues['billFileName']
                    , $formJsonValues['transactionDate']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->income->updateIncomeEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteIncomes($jsonData) {

        // delete entity using model
        $resultObject = $this->income->deleteSelectedIncomes($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllIncomes() {

        // delete entities using corresponding model
        $resultObject = $this->income->deleteAllIncomes();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }
    
    public function getAllIncomesByYear() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->income->selectAllIncomesByYear();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{' 
                        . '"currentMonth":"'.$resultObject[$i]["currentMonth"].'"'
                        . ',"sumIncomes":"'.$resultObject[$i]["sumIncomes"].'"'
                        . ',"currentYear":"'.$resultObject[$i]["currentYear"].'"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllIncomes();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewIncome($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $incomeId = $_POST['incomeId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateIncome($incomeId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteIncomes($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllIncomes();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['incomeId'])) {
                    $incomeId = $_POST['incomeId'];
                    $resultObject = $this->income->getIncomeDetails($incomeId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "addNewItem":
                //insert new entity
                $resultObject = Array('0' => Array(
                        eventId => ''
                        , title => ''
                        , amount => ''
                        , category => ''
                        , billFileName => ''
                        , transactionDate => ''
                    )
                );
                $postbackData = Utils::convertArrayToJson($resultObject[0]);
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['incomeId'])) {
                    $incomeId = $_POST['incomeId'];
                    $resultObject = $this->income->getIncomeDetails($incomeId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "getAllIncomesByYear":
                $postbackData = $this->getAllIncomesByYear();
                break;
        }
        return $postbackData;
    }

}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    $incomeController = new IncomeController($userAction);
    $incomeController->setUserAction($userAction);
    $postbackContent = $incomeController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

