 
<?php
/**
* This module was auto generated by GWatcho-Code generator
* The MemberRegistration controller entity class.
* @author
*    Guy Bami Watcho
*/
    include_once 'BaseController.php';
    class MemberRegistrationController extends BaseController {
        private $memberRegistration = null;
        /**
        * Constructor of the MemberRegistration controller
        * @param $userAction string the user action
        * @param $userRoles array the user roles
        */
        function __construct($userAction, $userRoles = array()) {
            parent::__construct($userAction, $userRoles);
            $this->memberRegistration = new MemberRegistration();
        }

       /**
        * Gets all MemberRegistration entities
        * @return mixed object having all MemberRegistration entities
        *    or string with the Exception details if error occured
        */
        public function getAllMemberRegistrations(){
            $itemSperator = ",";
            $entitiesList = "";
            $resultObject = $this->memberRegistration->selectAllMemberRegistrations();
            if (is_string($resultObject)) {
                return Utils::formatJsonErrorMessage($resultObject);
            } else if (is_array($resultObject)) {
                for ($i = 0; $i < count($resultObject); $i++) {
                    $entitiesList .= '{"registrationId":"' . $resultObject[$i]["registrationId"] . '"' . ',"memberId":"' . $resultObject[$i]["memberId"] . '"' . ',"code":"' . $resultObject[$i]["code"] . '"' . ',"sentDate":"' . $resultObject[$i]["sentDate"] . '"' . ',"confirmationDate":"' . $resultObject[$i]["confirmationDate"] . '"' . '}';
                    if ($i != count($resultObject) - 1) {
                        $entitiesList .= $itemSperator;
                    }
                }
                // close json list
                $entitiesList = "[" . $entitiesList . "]";
            }
            return $entitiesList;
        }

       /**
        * Inserts new MemberRegistration entity
        * @param mixed $jsonData json object entity to insert
        * @return mixed  true if insertion was successful
        *    or string with the Exception details if error occured
        */
        public function insertNewMemberRegistration($jsonData)
        {
            // get json posted values from request
            $formJsonValues = json_decode($jsonData, true);
            $postbackData = "";
            $resultObject = null;
            // insert entity using model object // $formJsonValues['sentDate']
            $resultObject = $this->memberRegistration->insertNewMemberRegistration($formJsonValues['memberId'], $formJsonValues['code'], 
                 Utils::formatFullDateUS(''), $formJsonValues['confirmationDate']);
            if (is_bool($resultObject) || is_int($resultObject)) {
                $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
                // send email
                $registrationId = $resultObject;
                $code = $formJsonValues["code"];
                $receiverMail = $formJsonValues["receiverMail"];
                
                $this->sendConfirmationRequestMail($receiverMail, $registrationId, $code);
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
            return $postbackData;
        }

       /**
        * Updates MemberRegistration entity via POST request
        * @param int $customerId
        * @param string $updateMode
        * @param mixed $jsonData
        * @return mixed  true if update was successful
        *    or string with the Exception details if error occured
        */
        public function updateMemberRegistration($registrationId, $updateMode, $jsonData){
            // get json posted values from request
            $formJsonValues = json_decode($jsonData, true);
            $postbackData = "";
            $resultObject = null;
            if ($updateMode == "allFields") {
                // update all entity fields
                $resultObject = $this->memberRegistration->updateMemberRegistrationDetails($registrationId, $formJsonValues['memberId'], $formJsonValues['code'], $formJsonValues['sentDate'], $formJsonValues['confirmationDate']);
                if (is_bool($resultObject)) {
                    if ($resultObject == true) {
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                    } else {
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                    }
                } else if (is_string($resultObject)) {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
            } else if ($updateMode == "inlineUpdate") {
                // Update entity from the datagrid
                $fieldName = $formJsonValues['fieldName'];
                $keyFieldValue = $formJsonValues['entityKeyId'];
                $newFieldValue = $formJsonValues['newFieldValue'];
                $resultObject = $this->memberRegistration->updateMemberRegistrationEntityField($fieldName, $keyFieldValue, $newFieldValue);
                if (is_string($resultObject)) {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_bool($resultObject)) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
                }
            }
            return $postbackData;
        }


        /**
            * Deletes all selected entities via POST request
            * @param mixed $jsonData all entities Id to delete
            * @return mixed
            */
        public function deleteMemberRegistrations($jsonData){
            // delete entity using model
            $resultObject = $this->memberRegistration->deleteSelectedMemberRegistrations($jsonData);
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else {
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
            return $postbackData;
        }
       
       /**
        * Deletes all entities
        * @param mixed $jsonData all entities Id to delete
        * @return mixed
        */
        public function deleteAllMemberRegistrations()
        {
            // delete entities using corresponding model
            $resultObject = $this->memberRegistration->deleteAllMemberRegistrations();
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else {
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
            return $postbackData;
        }

        private function sendConfirmationRequestMail($receiverMail, $registrationId, $code){
            $rootURL = Utils::getWebsiteRootURL();
            // test: http://localhost/KhevWeb/Controllers/MemberRegistrationController.php?userAction=confirmRegistrationFromEmail&registrationId=2&code=ZJ72y4vOOgzFY7LaoCtFYwQLIqbt8lmOdTAbLl9tocKGrkGcKF
            $pageLink = $rootURL . "Controllers/MemberRegistrationController.php?userAction=confirmRegistrationFromEmail&registrationId=".$registrationId."&code=".$code;
            Utils::sendConfirmRegistrationMail($receiverMail, $pageLink);      
        }


       /**
        * Get dynamic page content
        * @return mixed
        */
        public function getDynamicPageContent()
        {
            $postbackData = "Undefined Content";
            $resultObject = null;
            switch ($this->getUserAction()) {
                case "getAllItems":
                    $postbackData = $this->getAllMemberRegistrations();
                    break;
                case "addNewItem":
                case "insertNewItem":
                    $jsonData = array();
                    if (isset($_POST['formValues'])) {
                        $jsonData = $_POST['formValues'][0];
                    }
                    $postbackData = $this->insertNewMemberRegistration($jsonData);
                    break;
                case "updateItem":
                    $updateMode = "allFields";
                    if (isset($_POST['updateMode'])) {
                        $updateMode = $_POST['updateMode'];
                    }
                    $registrationId = $_POST['registrationId'];
                    $jsonData = $_POST['formValues'][0];
                    $postbackData = $this->updateMemberRegistration($registrationId, $updateMode, $jsonData);
                    break;
                case "deleteItem":
                    $jsonData = array();
                    if (isset($_POST['selectedIds'])) {
                        $jsonData = $_POST['selectedIds'];
                    }
                    $postbackData = $this->deleteMemberRegistrations($jsonData);
                    break;
                case "deleteAllItems":
                    $postbackData = $this->deleteAllMemberRegistrations();
                    break;
                case "editDetails":
                    $postbackData = "Undefined Content";
                    if (isset($_POST['registrationId'])) {
                        $registrationId = $_POST['registrationId'];
                        $resultObject = $this->memberRegistration->getMemberRegistrationDetails($registrationId);
                    }
                    if (is_string($resultObject)) {
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    } else if (is_array($resultObject)) {
                        $postbackData = Utils::convertArrayToJson($resultObject[0]);
                    }
                    break;
                case "viewDetails":
                case "cancelChanges":
                    if (isset($_POST['registrationId'])) {
                        $registrationId = $_POST['registrationId'];
                        $resultObject = $this->memberRegistration->getMemberRegistrationDetails($registrationId);
                    }
                    if (is_string($resultObject)) {
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    } else if (is_array($resultObject)) {
                        $postbackData = Utils::convertArrayToJson($resultObject[0]);
                    }
                    break;
                case "confirmRegistrationFromEmail":
                    // http://localhost/KhevWeb/Controllers/MemberRegistrationController.php?userAction=confirmRegistrationFromEmail&registrationId=2&code=ZJ72y4vOOgzFY7LaoCtFYwQLIqbt8lmOdTAbLl9tocKGrkGcKF
                    $date = new DateTime('', new DateTimeZone('Europe/Berlin'));
                    $updateMode = "inlineUpdate";
                    $registrationId = $_GET['registrationId'];
                    $code = $_GET['code'];
                    $jsonDataRaw = '[{"confirmationDate": "'. $date->format('Y-m-d H:i:s').'", "fieldName": "confirmationDate",
                        "$registrationId":"'. $registrationId.'" }]';

                    $arrayData = json_decode($jsonDataRaw, true);
                    $jsonData = $arrayData[0];
                    $confirmationDate = $date->format('Y-m-d H:i:s'); 
                    $resultObject = $this->memberRegistration->updateMemberRegistrationConfirmationDateFromMail($registrationId, $confirmationDate, $code);
                    if (is_string($resultObject)) {
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    } else if (is_bool($resultObject)) {
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
                        // go to registration view
                        $rootURL = Utils::getWebsiteRootURL();
                        $pageLink = $rootURL . "Views/Members/ViewMemberRegistration.php?status=registrationConfirmed&registrationId=" . $registrationId . "&code=" . $code;
                        echo "<script> window.location.href = '$pageLink'; </script>";
                    }

                    break;
            }
            return $postbackData;
        }
    }


    $userAction = null;
    if (isset($_POST) && isset($_POST['userAction'])) {
        $userAction = $_POST['userAction'];
    }
    else if (isset($_GET) && isset($_GET['userAction'])) {
        $userAction = $_GET['userAction'];
    }
    if (!isset($userAction)) {
        echo "No action has been set";
    } else {
        $memberRegistrationController = new MemberRegistrationController($userAction);
        $memberRegistrationController->setUserAction($userAction);
        $postbackContent = $memberRegistrationController->getDynamicPageContent();
        // send back content to client
        echo $postbackContent;
    }
