
<?php
    /**
        * This module was auto generated by GWatcho-Code generator
        * The MemberFee cotntroller entity class.
        * @author
        *    Guy Bami W.
        */
    include_once 'BaseController.php';
    class MemberFeeController extends BaseController {
        private $memberFee = null;

        /**
        * Constructor of the MemberFee controller
        * @param $userAction string the user action
        * @param $userRoles array the user roles
        */
        function __construct($userAction, $userRoles = array()) {
            parent::__construct($userAction, $userRoles);
            $this->memberFee = new MemberFee();
        }

        /**
        * Gets all MemberFee entities
        * @return mixed object having all MemberFee entities
        *    or string with the Exception details if error occured
        */
        public function getAllMemberFees() {
            $itemSperator = ",";
            $entitiesList = "";
            $resultObject = $this->memberFee->selectAllMemberFees();
            if (is_string($resultObject)) {
                return Utils::formatJsonErrorMessage($resultObject);
            } else if (is_array($resultObject)) {
                for ($i = 0; $i < count($resultObject); $i++) {
                    $entitiesList .= '{"memberFeeId":"' . $resultObject[$i]["memberFeeId"] . '"'  
                        . ',"memberId":"' . $resultObject[$i]["memberId"] . '"' . ',"amount":"' . $resultObject[$i]["amount"] . '"' 
                        . ',"billFileName":"' . $resultObject[$i]["billFileName"] . '"' 
                        . ',"transactionDate":"' . $resultObject[$i]["transactionDate"] . '"'
                        . ',"memberFullName":"' . $resultObject[$i]["lastName"] . ' ' . $resultObject[$i]["name"] . '"'
                        . '}';
                    if ($i != count($resultObject) - 1) {
                        $entitiesList .= $itemSperator;
                    }
                }
                // close json list
                $entitiesList = "[" . $entitiesList . "]";
            }
            return $entitiesList;
        }
        /**
        * Inserts new MemberFee entity
        * @param mixed $jsonData json object entity to insert
        * @return mixed  true if insertion was successful
        *    or string with the Exception details if error occured
        */
        public function insertNewMemberFee($jsonData) {
            // get json posted values from request
            $formJsonValues = json_decode($jsonData, true);
            $postbackData = "";
            $resultObject = null;
            // insert entity using model object
            $resultObject = $this->memberFee->insertNewMemberFee($formJsonValues['memberId'], $formJsonValues['amount'], $formJsonValues['billFileName'], $formJsonValues['transactionDate']);
            if (is_bool($resultObject) || is_int($resultObject)) {
                $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
            return $postbackData;
        }

        /**
        * Updates MemberFee entity via POST request
        * @param int $customerId
        * @param string $updateMode
        * @param mixed $jsonData
        * @return mixed  true if update was successful
        *    or string with the Exception details if error occured
        */
        public function updateMemberFee($memberFeeId, $updateMode, $jsonData) {
            // get json posted values from request
            $formJsonValues = json_decode($jsonData, true);
            $postbackData = "";
            $resultObject = null;
            if ($updateMode == "allFields") {
                // update all entity fields
                $resultObject = $this->memberFee->updateMemberFeeDetails($memberFeeId, $formJsonValues['memberId'], $formJsonValues['amount'], $formJsonValues['billFileName'], $formJsonValues['transactionDate']);
                if (is_bool($resultObject)) {
                    if ($resultObject == true) {
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                    } else {
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                    }
                } else if (is_string($resultObject)) {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
            } else if ($updateMode == "inlineUpdate") {
                // Update entity from the datagrid
                $fieldName = $formJsonValues['fieldName'];
                $keyFieldValue = $formJsonValues['entityKeyId'];
                $newFieldValue = $formJsonValues['newFieldValue'];
                $resultObject = $this->memberFee->updateMemberFeeEntityField($fieldName, $keyFieldValue, $newFieldValue);
                if (is_string($resultObject)) {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_bool($resultObject)) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
                }
            }
            return $postbackData;
        }
       /**
        * Deletes all selected entities via POST request
        * @param mixed $jsonData all entities Id to delete
        * @return mixed
        */
        public function deleteMemberFees($jsonData) {
            // delete entity using model
            $resultObject = $this->memberFee->deleteSelectedMemberFees($jsonData);
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else {
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
            return $postbackData;
        }


       /**
        * Deletes all entities
        * @param mixed $jsonData all entities Id to delete
        * @return mixed
        */
        public function deleteAllMemberFees() {
            // delete entities using corresponding model
            $resultObject = $this->memberFee->deleteAllMemberFees();
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else {
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
            return $postbackData;
        }

         
        /**
         * 
         * Get dynamic page content
         * @return mixed
         */
        public function getDynamicPageContent() {
            $postbackData = "Undefined Content";
            $resultObject = null;
            switch ($this->getUserAction()) {
                case "getAllItems":
                    $postbackData = $this->getAllMemberFees();
                    break;
                case "addNewItem":
                case "insertNewItem":
                    $jsonData = array();
                    if (isset($_POST['formValues'])) {
                        $jsonData = $_POST['formValues'][0];
                    }
                    $postbackData = $this->insertNewMemberFee($jsonData);
                    break;
                case "updateItem":
                    $updateMode = "allFields";
                    if (isset($_POST['updateMode'])) {
                        $updateMode = $_POST['updateMode'];
                    }
                    $memberFeeId = $_POST['memberFeeId'];
                    $jsonData = $_POST['formValues'][0];
                    $postbackData = $this->updateMemberFee($memberFeeId, $updateMode, $jsonData);
                    break;
                case "deleteItem":
                    $jsonData = array();
                    if (isset($_POST['selectedIds'])) {
                        $jsonData = $_POST['selectedIds'];
                    }
                    $postbackData = $this->deleteMemberFees($jsonData);
                    break;
                case "deleteAllItems":
                    $postbackData = $this->deleteAllMemberFees();
                    break;
                case "editDetails":
                    $postbackData = "Undefined Content";
                    if (isset($_POST['memberFeeId'])) {
                        $memberFeeId = $_POST['memberFeeId'];
                        $resultObject = $this->memberFee->getMemberFeeDetails($memberFeeId);
                    }
                    if (is_string($resultObject)) {
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    } else if (is_array($resultObject)) {
                        $postbackData = Utils::convertArrayToJson($resultObject[0]);
                    }
                    break;
                case "resetItem":
                    //insert new entity
                    $resultObject = array('0' => array(memberId => '', amount => '', billFileName => '', transactionDate => ''));
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                    break;
                case "viewDetails":
                case "cancelChanges":
                    if (isset($_POST['memberFeeId'])) {
                        $memberFeeId = $_POST['memberFeeId'];
                        $resultObject = $this->memberFee->getMemberFeeDetails($memberFeeId);
                    }
                    if (is_string($resultObject)) {
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    } else if (is_array($resultObject)) {
                        $postbackData = Utils::convertArrayToJson($resultObject[0]);
                    }
                    break;
            }
            return $postbackData;
        }
    }
    $userAction = null;
    if (isset($_POST) && isset($_POST['userAction'])) {
        $userAction = $_POST['userAction'];
    }
    if (!isset($userAction)) {
        echo "No action has been set";
    } else {
        $memberFeeController = new MemberFeeController($userAction);
        $memberFeeController->setUserAction($userAction);
        $postbackContent = $memberFeeController->getDynamicPageContent();
        // send back content to client
        echo $postbackContent;
    }
