
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The Member cotntroller entity class.
 * @author
 *    Guy Bami
 */
include_once 'BaseController.php';

class MemberController extends BaseController {

    private $member = null;

    /**
     * Constructor of the Member controller 

     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->member = new Member();
    }

    /**
     * Gets all Member entities
     * @return mixed object having all Member entities
     *    or string with the Exception details if error occured
     */
    public function getAllMembers() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->member->selectAllMembers();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"memberId":"' . $resultObject[$i]["memberId"] . '"'
                        . ',"gender":"' . $resultObject[$i]["gender"] . '"'
                        . ',"name":"' . $resultObject[$i]["name"] . '"'
                        . ',"lastName":"' . $resultObject[$i]["lastName"] . '"'
                        . ',"email":"' . $resultObject[$i]["email"] . '"'
                        . ',"phoneNumber":"' . $resultObject[$i]["phoneNumber"] . '"'
                        . ',"zipCode":"' . $resultObject[$i]["zipCode"] . '"'
                        . ',"city":"' . $resultObject[$i]["city"] . '"'
                        . ',"address":"' . $resultObject[$i]["address"] . '"'
                        . ',"position":"' . $resultObject[$i]["position"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new Member entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewMember($jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->member->insertNewMember(
                $formJsonValues['gender']
                , $formJsonValues['name']
                , $formJsonValues['lastName']
                , $formJsonValues['email']
                , $formJsonValues['phoneNumber']
                , $formJsonValues['zipCode']
                , $formJsonValues['city']
                , $formJsonValues['address']
                , $formJsonValues['position']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates Member entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateMember($memberId, $updateMode, $jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->member->updateMemberDetails(
                    $memberId
                    , $formJsonValues['gender']
                    , $formJsonValues['name']
                    , $formJsonValues['lastName']
                    , $formJsonValues['email']
                    , $formJsonValues['phoneNumber']
                    , $formJsonValues['zipCode']
                    , $formJsonValues['city']
                    , $formJsonValues['address']
                    , $formJsonValues['position']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->member->updateMemberEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteMembers($jsonData) {

        // delete entity using model
        $resultObject = $this->member->deleteSelectedMembers($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllMembers() {

        // delete entities using corresponding model
        $resultObject = $this->member->deleteAllMembers();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllMembers();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewMember($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $memberId = $_POST['memberId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateMember($memberId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteMembers($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllMembers();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['memberId'])) {
                    $memberId = $_POST['memberId'];
                    $resultObject = $this->member->getMemberDetails($memberId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "addNewItemTest":
                //insert new entity
                $resultObject = Array('0' => Array(
                        gender => ''
                        , name => ''
                        , lastName => ''
                        , email => ''
                        , phoneNumber => ''
                        , zipCode => ''
                        , city => ''
                        , address => ''
                        , position => ''
                    )
                );
                $postbackData = Utils::convertArrayToJson($resultObject[0]);
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['memberId'])) {
                    $memberId = $_POST['memberId'];
                    $resultObject = $this->member->getMemberDetails($memberId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
        }
        return $postbackData;
    }

}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    $memberController = new MemberController($userAction);
    $memberController->setUserAction($userAction);
    $postbackContent = $memberController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

