
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The OldExam cotntroller entity class.
 * @author
 *    Guy Bami W.
 */
include_once 'BaseController.php';

class OldExamController extends BaseController {

    private $oldExam = null;

    /**
     * Constructor of the OldExam controller 

     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->oldExam = new OldExam();
    }

    /**
     * Gets all OldExam entities
     * @return mixed object having all OldExam entities
     *    or string with the Exception details if error occured
     */
    public function getAllOldExams() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->oldExam->selectAllOldExams();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"examId":"' . $resultObject[$i]["examId"] . '"'
                        . ',"userId":"' . $resultObject[$i]["userId"] . '"'
                        . ',"subject":"' . $resultObject[$i]["subject"] . '"'
                        . ',"title":"' . $resultObject[$i]["title"] . '"'
                        . ',"semester":"' . $resultObject[$i]["semester"] . '"'
                        . ',"date":"' . $resultObject[$i]["date"] . '"'
                        . ',"fileFullName":"' . $resultObject[$i]["fileFullName"] . '"'
                        // foreign fields
                        . ',"name":"' . $resultObject[$i]["name"] . '"'
                        . ',"lastName":"' . $resultObject[$i]["lastName"] . '"'
                        . ',"phoneNumber":"' . $resultObject[$i]["phoneNumber"] . '"'
                        . ',"email":"' . $resultObject[$i]["email"] . '"'
                        . ',"userFullName":"' . $resultObject[$i]["lastName"] . " " . $resultObject[$i]["name"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new OldExam entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewOldExam($jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->oldExam->insertNewOldExam(
                $formJsonValues['userId']
                , $formJsonValues['subject']
                , $formJsonValues['title']
                , $formJsonValues['semester']
                , $formJsonValues['date']
                , $formJsonValues['fileFullName']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates OldExam entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateOldExam($examId, $updateMode, $jsonData) {

        // get json posted values from request
        $formJsonValues = json_decode($jsonData, true);
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->oldExam->updateOldExamDetails(
                    $examId
                    , $formJsonValues['userId']
                    , $formJsonValues['subject']
                    , $formJsonValues['title']
                    , $formJsonValues['semester']
                    , $formJsonValues['date']
                    , $formJsonValues['fileFullName']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->oldExam->updateOldExamEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteOldExams($jsonData) {

        // delete entity using model
        $resultObject = $this->oldExam->deleteSelectedOldExams($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllOldExams() {

        // delete entities using corresponding model
        $resultObject = $this->oldExam->deleteAllOldExams();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllOldExams();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewOldExam($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $examId = $_POST['examId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateOldExam($examId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteOldExams($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllOldExams();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['examId'])) {
                    $examId = $_POST['examId'];
                    $resultObject = $this->oldExam->getOldExamDetails($examId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "addNewItem":
                //insert new entity
                $resultObject = Array('0' => Array(
                        userId => ''
                        , subject => ''
                        , title => ''
                        , semester => ''
                        , date => ''
                        , fileFullName => ''
                    )
                );
                $postbackData = Utils::convertArrayToJson($resultObject[0]);
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['examId'])) {
                    $examId = $_POST['examId'];
                    $resultObject = $this->oldExam->getOldExamDetails($examId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
        }
        return $postbackData;
    }

}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    $oldExamController = new OldExamController($userAction);
    $oldExamController->setUserAction($userAction);
    $postbackContent = $oldExamController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

