
            <?php 


               /**
                * This module was auto generated by GWatcho-Code generator
                * The RoleAccessRight cotntroller entity class.
                * @author
                *    Guy Bami W.
                */

  
include_once 'BaseController.php';


 class RoleAccessRightController extends BaseController { 
private $roleAccessRight = null; 


                 /**
                  *Constructor of the RoleAccessRight controller 

                   * @param $userAction string the user action
* @param $userRoles array the user roles 
                  */
                
function __construct($userAction, $userRoles = array()){ 
     parent::__construct($userAction, $userRoles);
                        $this->roleAccessRight = new RoleAccessRight(); }


           /**
            * Gets all RoleAccessRight entities
            * @return mixed object having all RoleAccessRight entities
            *    or string with the Exception details if error occured
            */
            public function getAllRoleAccessRights(){

                $itemSperator = ",";
                $entitiesList = "";
                $resultObject = $this->roleAccessRight->selectAllRoleAccessRights();
                if(is_string($resultObject)){
                    return Utils::formatJsonErrorMessage($resultObject);
                }
                else if(is_array($resultObject)){
                    for ($i = 0; $i < count($resultObject); $i++)
                    {
                        $entitiesList .= 
'{"roleAccessId":"'.$resultObject[$i]["roleAccessId"].'"'
.',"roleId":"'.$resultObject[$i]["roleId"].'"'
.',"entityType":"'.$resultObject[$i]["entityType"].'"'
.',"createRight":"'.$resultObject[$i]["createRight"].'"'
.',"readRight":"'.$resultObject[$i]["readRight"].'"'
.',"editRight":"'.$resultObject[$i]["editRight"].'"'
.',"deleteRight":"'.$resultObject[$i]["deleteRight"].'"'
.',"fullRight":"'.$resultObject[$i]["fullRight"].'"'
.'}';

                        if ($i != count($resultObject) - 1) {
                            $entitiesList .= $itemSperator;
                        }
                    }
                    // close json list
                    $entitiesList = "[" . $entitiesList . "]";

                }
                return $entitiesList;

            }


           /**
             * Inserts new RoleAccessRight entity
             * @param mixed $jsonData json object entity to insert
             * @return mixed  true if insertion was successful
             *    or string with the Exception details if error occured
             */
            public function insertNewRoleAccessRight($jsonData){

                // get json posted values from request
                $formJsonValues = json_decode($jsonData, true);
                $postbackData = "";
                $resultObject = null;
                // insert entity using model object
                $resultObject = $this->roleAccessRight->insertNewRoleAccessRight(
                                $formJsonValues['roleId']
,$formJsonValues['entityType']
,$formJsonValues['createRight']
,$formJsonValues['readRight']
,$formJsonValues['editRight']
,$formJsonValues['deleteRight']
,$formJsonValues['fullRight']


                );

                if(is_bool($resultObject) || is_int($resultObject)){
                    $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Updates RoleAccessRight entity via POST request
             * @param int $customerId
             * @param string $updateMode
             * @param mixed $jsonData
             * @return mixed  true if update was successful
             *    or string with the Exception details if error occured
             */
            public function updateRoleAccessRight($roleAccessId, $updateMode, $jsonData){

                // get json posted values from request
                $formJsonValues = json_decode($jsonData, true);
                $postbackData = "";
                $resultObject = null;
                if ($updateMode == "allFields") {
                    // update all entity fields
                    $resultObject = $this->roleAccessRight->updateRoleAccessRightDetails(
                                  $roleAccessId
,$formJsonValues['roleId']
,$formJsonValues['entityType']
,$formJsonValues['createRight']
,$formJsonValues['readRight']
,$formJsonValues['editRight']
,$formJsonValues['deleteRight']
,$formJsonValues['fullRight']


                    );
                    if(is_bool($resultObject)){
                        if($resultObject == true){
                            $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                        }
                        else{
                            $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                        }
                    }
                    else if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }

                }
                else if ($updateMode == "inlineUpdate") {
                    // Update entity from the datagrid
                    $fieldName = $formJsonValues['fieldName'];
                    $keyFieldValue = $formJsonValues['entityKeyId'];
                    $newFieldValue = $formJsonValues['newFieldValue'];
                    $resultObject = $this->roleAccessRight->updateRoleAccessRightEntityField($fieldName, $keyFieldValue, $newFieldValue);
                    if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }
                    else if(is_bool($resultObject)){
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
                    }
                }
                return $postbackData;

            }


           /**
             * Deletes all selected entities via POST request
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteRoleAccessRights($jsonData){

                // delete entity using model
                $resultObject = $this->roleAccessRight->deleteSelectedRoleAccessRights($jsonData);
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Deletes all entities
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteAllRoleAccessRights(){

                // delete entities using corresponding model
                $resultObject = $this->roleAccessRight->deleteAllRoleAccessRights();
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Get dynamic page content
             * @return mixed
             */
            public function getDynamicPageContent() {

                $postbackData = "Undefined Content";
                $resultObject = null;
                switch ($this->getUserAction()) {
                    case "getAllItems":
                        $postbackData = $this->getAllRoleAccessRights();
                        break;
                    case "addNewItem":
                    case "insertNewItem":
                        $jsonData = array();
                        if (isset($_POST['formValues'])) {
                            $jsonData = $_POST['formValues'][0];
                        }
                        $postbackData = $this->insertNewRoleAccessRight($jsonData);
                        break;
                    case "updateItem":
                        $updateMode = "allFields";
                        if (isset($_POST['updateMode'])) {
                            $updateMode = $_POST['updateMode'];
                        }
                        $roleAccessId = $_POST['roleAccessId'];
                        $jsonData = $_POST['formValues'][0];
                        $postbackData = $this->updateRoleAccessRight($roleAccessId, $updateMode, $jsonData);
                        break;
                    case "deleteItem":
                        $jsonData = array();
                        if (isset($_POST['selectedIds'])) {
                            $jsonData = $_POST['selectedIds'];
                        }
                        $postbackData = $this->deleteRoleAccessRights($jsonData);
                        break;
                    case "deleteAllItems":
                        $postbackData = $this->deleteAllRoleAccessRights();
                        break;
                    case "editDetails":
                        $postbackData = "Undefined Content";
                        if ( isset($_POST['roleAccessId']) ) {
                            $roleAccessId = $_POST['roleAccessId'];
                            $resultObject = $this->roleAccessRight->getRoleAccessRightDetails($roleAccessId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                    case "addNewItem":
                        //insert new entity
                        $resultObject = Array('0' => Array(
                             roleId=>''
,entityType=>''
,createRight=>''
,readRight=>''
,editRight=>''
,deleteRight=>''
,fullRight=>''


                           )
                        );
                        $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        break;
                    case "viewDetails":
                    case "cancelChanges":
                        if ( isset($_POST['roleAccessId']) ) {
                            $roleAccessId = $_POST['roleAccessId'];
                            $resultObject = $this->roleAccessRight->getRoleAccessRightDetails($roleAccessId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                }
                return $postbackData;

            }

} 


            $userAction = null;
            if (isset($_POST) && isset($_POST['userAction'])) {
                $userAction = $_POST['userAction'];
            }
            if (!isset($userAction)) {
                echo "No action has been set";
            }
            else{
                $roleAccessRightController = new RoleAccessRightController($userAction);
                $roleAccessRightController->setUserAction($userAction);
                $postbackContent = $roleAccessRightController->getDynamicPageContent();

                // send back content to client
                echo $postbackContent;
            }
            

