
            <?php 


               /**
                * This module was auto generated by GWatcho-Code generator
                * The Tutorial cotntroller entity class.
                * @author
                *    Guy Bami W.
                */

  
include_once 'BaseController.php';


 class TutorialController extends BaseController { 
private $tutorial = null; 


                 /**
                  *Constructor of the Tutorial controller 

                   * @param $userAction string the user action
* @param $userRoles array the user roles 
                  */
                
function __construct($userAction, $userRoles = array()){ 
     parent::__construct($userAction, $userRoles);
                        $this->tutorial = new Tutorial(); }


           /**
            * Gets all Tutorial entities
            * @return mixed object having all Tutorial entities
            *    or string with the Exception details if error occured
            */
            public function getAllTutorials(){

                $itemSperator = ",";
                $entitiesList = "";
                $resultObject = $this->tutorial->selectAllTutorials();
                if(is_string($resultObject)){
                    return Utils::formatJsonErrorMessage($resultObject);
                }
                else if(is_array($resultObject)){
                    for ($i = 0; $i < count($resultObject); $i++)
                    {
                        $entitiesList .= 
'{"tutorialId":"'.$resultObject[$i]["tutorialId"].'"'
.',"memberId":"'.$resultObject[$i]["memberId"].'"'
.',"date":"'.$resultObject[$i]["date"].'"'
.',"subject":"'.$resultObject[$i]["subject"].'"'
.',"level":"'.$resultObject[$i]["level"].'"'
.',"location":"'.$resultObject[$i]["location"].'"'
.',"shedules":"'.$resultObject[$i]["shedules"].'"'
.',"status":"'.$resultObject[$i]["status"].'"'
.'}';

                        if ($i != count($resultObject) - 1) {
                            $entitiesList .= $itemSperator;
                        }
                    }
                    // close json list
                    $entitiesList = "[" . $entitiesList . "]";

                }
                return $entitiesList;

            }


           /**
             * Inserts new Tutorial entity
             * @param mixed $jsonData json object entity to insert
             * @return mixed  true if insertion was successful
             *    or string with the Exception details if error occured
             */
            public function insertNewTutorial($jsonData){

                // get json posted values from request
                $formJsonValues = json_decode($jsonData, true);
                $postbackData = "";
                $resultObject = null;
                // insert entity using model object
                $resultObject = $this->tutorial->insertNewTutorial(
                                $formJsonValues['memberId']
,$formJsonValues['date']
,$formJsonValues['subject']
,$formJsonValues['level']
,$formJsonValues['location']
,$formJsonValues['shedules']
,$formJsonValues['status']


                );

                if(is_bool($resultObject) || is_int($resultObject)){
                    $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Updates Tutorial entity via POST request
             * @param int $customerId
             * @param string $updateMode
             * @param mixed $jsonData
             * @return mixed  true if update was successful
             *    or string with the Exception details if error occured
             */
            public function updateTutorial($tutorialId, $updateMode, $jsonData){

                // get json posted values from request
                $formJsonValues = json_decode($jsonData, true);
                $postbackData = "";
                $resultObject = null;
                if ($updateMode == "allFields") {
                    // update all entity fields
                    $resultObject = $this->tutorial->updateTutorialDetails(
                                  $tutorialId
,$formJsonValues['memberId']
,$formJsonValues['date']
,$formJsonValues['subject']
,$formJsonValues['level']
,$formJsonValues['location']
,$formJsonValues['shedules']
,$formJsonValues['status']


                    );
                    if(is_bool($resultObject)){
                        if($resultObject == true){
                            $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                        }
                        else{
                            $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                        }
                    }
                    else if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }

                }
                else if ($updateMode == "inlineUpdate") {
                    // Update entity from the datagrid
                    $fieldName = $formJsonValues['fieldName'];
                    $keyFieldValue = $formJsonValues['entityKeyId'];
                    $newFieldValue = $formJsonValues['newFieldValue'];
                    $resultObject = $this->tutorial->updateTutorialEntityField($fieldName, $keyFieldValue, $newFieldValue);
                    if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }
                    else if(is_bool($resultObject)){
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
                    }
                }
                return $postbackData;

            }


           /**
             * Deletes all selected entities via POST request
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteTutorials($jsonData){

                // delete entity using model
                $resultObject = $this->tutorial->deleteSelectedTutorials($jsonData);
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Deletes all entities
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteAllTutorials(){

                // delete entities using corresponding model
                $resultObject = $this->tutorial->deleteAllTutorials();
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Get dynamic page content
             * @return mixed
             */
            public function getDynamicPageContent() {

                $postbackData = "Undefined Content";
                $resultObject = null;
                switch ($this->getUserAction()) {
                    case "getAllItems":
                        $postbackData = $this->getAllTutorials();
                        break;
                    case "addNewItem":
                    case "insertNewItem":
                        $jsonData = array();
                        if (isset($_POST['formValues'])) {
                            $jsonData = $_POST['formValues'][0];
                        }
                        $postbackData = $this->insertNewTutorial($jsonData);
                        break;
                    case "updateItem":
                        $updateMode = "allFields";
                        if (isset($_POST['updateMode'])) {
                            $updateMode = $_POST['updateMode'];
                        }
                        $tutorialId = $_POST['tutorialId'];
                        $jsonData = $_POST['formValues'][0];
                        $postbackData = $this->updateTutorial($tutorialId, $updateMode, $jsonData);
                        break;
                    case "deleteItem":
                        $jsonData = array();
                        if (isset($_POST['selectedIds'])) {
                            $jsonData = $_POST['selectedIds'];
                        }
                        $postbackData = $this->deleteTutorials($jsonData);
                        break;
                    case "deleteAllItems":
                        $postbackData = $this->deleteAllTutorials();
                        break;
                    case "editDetails":
                        $postbackData = "Undefined Content";
                        if ( isset($_POST['tutorialId']) ) {
                            $tutorialId = $_POST['tutorialId'];
                            $resultObject = $this->tutorial->getTutorialDetails($tutorialId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                    case "addNewItem":
                        //insert new entity
                        $resultObject = Array('0' => Array(
                             memberId=>''
,date=>''
,subject=>''
,level=>''
,location=>''
,shedules=>''
,status=>''


                           )
                        );
                        $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        break;
                    case "viewDetails":
                    case "cancelChanges":
                        if ( isset($_POST['tutorialId']) ) {
                            $tutorialId = $_POST['tutorialId'];
                            $resultObject = $this->tutorial->getTutorialDetails($tutorialId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                }
                return $postbackData;

            }

} 


            $userAction = null;
            if (isset($_POST) && isset($_POST['userAction'])) {
                $userAction = $_POST['userAction'];
            }
            if (!isset($userAction)) {
                echo "No action has been set";
            }
            else{
                $tutorialController = new TutorialController($userAction);
                $tutorialController->setUserAction($userAction);
                $postbackContent = $tutorialController->getDynamicPageContent();

                // send back content to client
                echo $postbackContent;
            }
            

