
<?php


/**
 * This module was auto generated by GWatcho-Code generator
 * @author
 *    Guy Bami
 */


include_once 'BaseController.php';
include_once '../Includes/CustomFileUploader.php';


class UploadFileController extends BaseController {
    private $customFileUploader = null;


    /**
     *Constructor of the UploadFile controller
     * @param $userAction string the user action
     * @param $userRoles array the user roles
     */
    function __construct($userAction, $userRoles = array()){
        parent::__construct($userAction, $userRoles);
        //$this->customFileUploader = new CustomFileUploader();
    }


     

    /**
     * uploads multiple images files  
     * @param mixed $filesListToUpload array object  with files to upload
     * @return mixed  true if upload was successful
     *    or string with the Exception details if error occured
     */
    public function uploadAllImageFiles($filesListToUpload){

        $postbackData = "";
        $resultObject = null;
        $this->customFileUploader = new CustomFileUploader($filesListToUpload);
        // insert entity using model object
        $resultObject = $this->customFileUploader->uploadAllImageFiles();
        $postbackData = json_encode($resultObject, true);
        
        return $postbackData;

    }

    public function uploadVideoFile($videoToUpload){

        $postbackData = "";
        $resultObject = null;
        $this->customFileUploader = new CustomFileUploader();
        $resultObject = $this->customFileUploader->uploadVideoFile($videoToUpload);
        $postbackData = json_encode($resultObject, true);
        return $postbackData;

    }

    public static function rearrangeArrayFiles($filesToRearrange)
    {
        $fileArrayRearranged = array();
        $filesCount = count($filesToRearrange['name']);
        $fileKeys = array_keys($filesToRearrange);
        //echo "count: " . $filesCount;
        for($i = 0; $i < $filesCount; $i++)
        {
            foreach($fileKeys as $key)
            {
                $fileArrayRearranged[$i][$key] = $filesToRearrange[$key][$i];
            }
        }
        return $fileArrayRearranged;
    }
     

    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = Utils::formatJsonErrorMessage("Undefined Content");
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "uploadImage":
                $filesToUpload = $_FILES['filesToUpload'];
                $filesToUpload = UploadFileController::rearrangeArrayFiles($_FILES["filesToUpload"]);
                //print_r($filesToUpload);
                $postbackData = $this->uploadAllImageFiles($filesToUpload);
                break;
            case "uploadVideo":
                $videoToUpload = $_FILES['videoToUpload'];
                print_r($videoToUpload);
                //$videoToUpload = UploadFileController::rearrangeArrayFiles($_FILES["videoToUpload"]);
                $postbackData = $this->uploadVideoFile($videoToUpload);
                break;
        }
        return $postbackData;
    }

}


//echo "Max: " . file_upload_max_size();
  //return;


// print_r($_FILES );
  //$filesToRearrange = UploadFileController::rearrangeArrayFiles($_FILES["filesToUpload"]);
  //print_r($filesToRearrange);

  

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
}
else{
    $uploadFileController = new UploadFileController($userAction);
    $uploadFileController->setUserAction($userAction);
    $postbackContent =   $uploadFileController->getDynamicPageContent();
    // clear previous content
    // send back content to client
    echo $postbackContent;
}


