
<?php


/**
 * This module was auto generated by the G-Watcho module generator
 * The Conference model entity class.
 * @author
 *    Guy Bami
 */

include_once '../Utils/ExceptionLogger.php';


class Conference{
    private $conferenceId;
    private $date;
    private $title;
    private $location;
    private $summary;

    /** Constructor of an Conference object
     *  @param $conferenceId int The entity  primary key field
     * @param  $date string The entity  date field
     * @param  $title string The entity  title field
     * @param  $location string The entity  location field
     * @param  $summary string The entity  summary field
     */

    function __construct($conferenceId = "", $date = "", $title = "", $location = "", $summary = ""){
        $this->conferenceId = $conferenceId;
        $this->date = $date;
        $this->title = $title;
        $this->location = $location;
        $this->summary = $summary;
    }



    /**
     * Gets  $date value
     * @param $date
     * @return mixed
     */
    public function getDate() {
        return $this->date;
    }



    /**
     * Gets  $title value
     * @param $title
     * @return mixed
     */
    public function getTitle() {
        return $this->title;
    }



    /**
     * Gets  $location value
     * @param $location
     * @return mixed
     */
    public function getLocation() {
        return $this->location;
    }



    /**
     * Gets  $summary value
     * @param $summary
     * @return mixed
     */
    public function getSummary() {
        return $this->summary;
    }



    /**
     * Sets  $date value
     * @param $date
     * @return void
     */
    public function setDate($date) {
        $this->date = $date;
    }



    /**
     * Sets  $title value
     * @param $title
     * @return void
     */
    public function setTitle($title) {
        $this->title = $title;
    }



    /**
     * Sets  $location value
     * @param $location
     * @return void
     */
    public function setLocation($location) {
        $this->location = $location;
    }



    /**
     * Sets  $summary value
     * @param $summary
     * @return void
     */
    public function setSummary($summary) {
        $this->summary = $summary;
    }


    /**
     * Selects all Conference items
     * @return
     *   array The object having all Conference items
     *    or string with the Exception details if error occured
     */
    public function selectAllConferences(){
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllConferences();
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Gets Conference item
     * @param $conferenceId int  The table primary key
     * @return
     *   array The object with the given $conferenceId value
     */
    public function getConferenceDetails($conferenceId){
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectConferenceDetails($conferenceId);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Inserts new Conference entity
     * @param  $date string The entity  date field
     * @param   $title string The entity  title field
     * @param   $location string The entity  location field
     * @param   $summary string The entity  summary field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewConference($date, $title, $location, $summary){
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewConference($date, $title, $location, $summary);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Updates Conference item
     * @param  $conferenceId int The entity  conferenceId field
     * @param  $date string The entity  date field
     * @param  $title string The entity  title field
     * @param  $location string The entity  location field
     * @param  $summary string The entity  summary field
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateConference($conferenceId, $date, $title, $location, $summary){
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateConference($conferenceId, $date, $title, $location, $summary);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Updates Conference item  details

     * @param  $conferenceId int The entity  conferenceId field
     * @param  $date string The entity  date field
     * @param  $title string The entity  title field
     * @param  $location string The entity  location field
     * @param  $summary string The entity  summary field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateConferenceDetails($conferenceId, $date, $title, $location, $summary){
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateConferenceDetails($conferenceId, $date, $title, $location, $summary);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Updates date of the Conference entity
     * @param   $conferenceId int The entity  conferenceId field
     * @param   $date string The entity  date field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateConferenceDate($conferenceId, $date){
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateConferenceDate($conferenceId, $date);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Updates title of the Conference entity
     * @param   $conferenceId int The entity  conferenceId field
     * @param   $title string The entity  title field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateConferenceTitle($conferenceId, $title){
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateConferenceTitle($conferenceId, $title);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Updates location of the Conference entity
     * @param   $conferenceId int The entity  conferenceId field
     * @param   $location string The entity  location field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateConferenceLocation($conferenceId, $location){
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateConferenceLocation($conferenceId, $location);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Updates summary of the Conference entity
     * @param   $conferenceId int The entity  conferenceId field
     * @param   $summary string The entity  summary field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateConferenceSummary($conferenceId, $summary){
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateConferenceSummary($conferenceId, $summary);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Updates specific field of the Conference item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateConferenceEntityField($fieldName, $keyFieldValue, $newFieldValue){
        try {
            switch($fieldName){

                case "date":
                    return $this->updateConferenceDate($keyFieldValue, $newFieldValue);

                case "title":
                    return $this->updateConferenceTitle($keyFieldValue, $newFieldValue);

                case "location":
                    return $this->updateConferenceLocation($keyFieldValue, $newFieldValue);

                case "summary":
                    return $this->updateConferenceSummary($keyFieldValue, $newFieldValue);

            }
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }


    /**
     * Deletes Conference item
     * @param  $conferenceId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteConference($conferenceId){
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteConference($conferenceId);
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


    /**
     * Deletes selected Conference items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedConferences($selectedItemsId){

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)){
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteConference($itemId)) {
                    continue;
                }
                else {
                    return "error: Can not delete Conference !";
                }
            }
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }


    /**
     * Deletes all Conference items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllConferences(){
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllConferences();
        }
        catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }


}

