
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The EventVideo model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class EventVideo {

    private $videoId;
    private $eventId;
    private $fileFullName;
    private $title;

    /** Constructor of an EventVideo object
     *  @param $videoId int The entity  primary key field 
     * @param  $eventId int The entity  eventId field 
     * @param  $fileFullName string The entity  fileFullName field 
     * @param  $title string The entity  title field 
     */
    function __construct($videoId = "", $eventId = "", $fileFullName = "", $title = "") {
        $this->videoId = $videoId;
        $this->eventId = $eventId;
        $this->fileFullName = $fileFullName;
        $this->title = $title;
    }

    /**
     * Gets  $eventId value
     * @param $eventId
     * @return mixed
     */
    public function getEventId() {
        return $this->eventId;
    }

    /**
     * Gets  $fileFullName value
     * @param $fileFullName
     * @return mixed
     */
    public function getFileFullName() {
        return $this->fileFullName;
    }

    /**
     * Gets  $title value
     * @param $title
     * @return mixed
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Sets  $eventId value
     * @param $eventId
     * @return void
     */
    public function setEventId($eventId) {
        $this->eventId = $eventId;
    }

    /**
     * Sets  $fileFullName value
     * @param $fileFullName
     * @return void
     */
    public function setFileFullName($fileFullName) {
        $this->fileFullName = $fileFullName;
    }

    /**
     * Sets  $title value
     * @param $title
     * @return void
     */
    public function setTitle($title) {
        $this->title = $title;
    }

    /**
     * Selects all EventVideo items
     * @return
     *   array The object having all EventVideo items
     *    or string with the Exception details if error occured
     */
    public function selectAllEventVideos() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllEventVideos();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets EventVideo item
     * @param $videoId int  The table primary key
     * @return
     *   array The object with the given $videoId value
     */
    public function getEventVideoDetails($videoId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectEventVideoDetails($videoId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new EventVideo entity
     * @param  $eventId int The entity  eventId field 
     * @param   $fileFullName string The entity  fileFullName field
     * @param   $title string The entity  title field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewEventVideo($eventId, $fileFullName, $title) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewEventVideo($eventId, $fileFullName, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates EventVideo item
     * @param  $videoId int The entity  videoId field 
     * @param  $eventId int The entity  eventId field 
     * @param  $fileFullName string The entity  fileFullName field 
     * @param  $title string The entity  title field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideo($videoId, $eventId, $fileFullName, $title) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideo($videoId, $eventId, $fileFullName, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates EventVideo item  details

     * @param  $videoId int The entity  videoId field 
     * @param  $eventId int The entity  eventId field 
     * @param  $fileFullName string The entity  fileFullName field 
     * @param  $title string The entity  title field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoDetails($videoId, $eventId, $fileFullName, $title) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoDetails($videoId, $eventId, $fileFullName, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates eventId of the EventVideo entity
     * @param   $videoId int The entity  videoId field 
     * @param   $eventId int The entity  eventId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoEventId($videoId, $eventId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoEventId($videoId, $eventId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates fileFullName of the EventVideo entity
     * @param   $videoId int The entity  videoId field 
     * @param   $fileFullName string The entity  fileFullName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoFileFullName($videoId, $fileFullName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoFileFullName($videoId, $fileFullName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates title of the EventVideo entity
     * @param   $videoId int The entity  videoId field 
     * @param   $title string The entity  title field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoTitle($videoId, $title) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoTitle($videoId, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the EventVideo item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "eventId":
                    return $this->updateEventVideoEventId($keyFieldValue, $newFieldValue);

                case "fileFullName":
                    return $this->updateEventVideoFileFullName($keyFieldValue, $newFieldValue);

                case "title":
                    return $this->updateEventVideoTitle($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes EventVideo item
     * @param  $videoId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteEventVideo($videoId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteEventVideo($videoId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected EventVideo items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedEventVideos($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteEventVideo($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete EventVideo !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all EventVideo items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllEventVideos() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllEventVideos();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
