
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The EventBillSummary model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class EventBillSummary {

    private $billSummaryId;
    private $eventId;
    private $title;
    private $summary;
    private $summaryFileName;

    /** Constructor of an EventBillSummary object
     *  @param $billSummaryId int The entity  primary key field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $summary string The entity  summary field 
     * @param  $summaryFileName string The entity  summaryFileName field 
     */
    function __construct($billSummaryId = "", $eventId = "", $title = "", $summary = "", $summaryFileName = "") {
        $this->billSummaryId = $billSummaryId;
        $this->eventId = $eventId;
        $this->title = $title;
        $this->summary = $summary;
        $this->summaryFileName = $summaryFileName;
    }

    /**
     * Gets  $eventId value
     * @param $eventId
     * @return mixed
     */
    public function getEventId() {
        return $this->eventId;
    }

    /**
     * Gets  $title value
     * @param $title
     * @return mixed
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Gets  $summary value
     * @param $summary
     * @return mixed
     */
    public function getSummary() {
        return $this->summary;
    }

    /**
     * Gets  $summaryFileName value
     * @param $summaryFileName
     * @return mixed
     */
    public function getSummaryFileName() {
        return $this->summaryFileName;
    }

    /**
     * Sets  $eventId value
     * @param $eventId
     * @return void
     */
    public function setEventId($eventId) {
        $this->eventId = $eventId;
    }

    /**
     * Sets  $title value
     * @param $title
     * @return void
     */
    public function setTitle($title) {
        $this->title = $title;
    }

    /**
     * Sets  $summary value
     * @param $summary
     * @return void
     */
    public function setSummary($summary) {
        $this->summary = $summary;
    }

    /**
     * Sets  $summaryFileName value
     * @param $summaryFileName
     * @return void
     */
    public function setSummaryFileName($summaryFileName) {
        $this->summaryFileName = $summaryFileName;
    }

    /**
     * Selects all EventBillSummary items
     * @return
     *   array The object having all EventBillSummary items
     *    or string with the Exception details if error occured
     */
    public function selectAllEventBillSummaries() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllEventBillSummaries();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets EventBillSummary item
     * @param $billSummaryId int  The table primary key
     * @return
     *   array The object with the given $billSummaryId value
     */
    public function getEventBillSummaryDetails($billSummaryId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectEventBillSummaryDetails($billSummaryId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new EventBillSummary entity
     * @param  $eventId int The entity  eventId field 
     * @param   $title string The entity  title field
     * @param   $summary string The entity  summary field
     * @param   $summaryFileName string The entity  summaryFileName field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewEventBillSummary($eventId, $title, $summary, $summaryFileName) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewEventBillSummary($eventId, $title, $summary, $summaryFileName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates EventBillSummary item
     * @param  $billSummaryId int The entity  billSummaryId field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $summary string The entity  summary field 
     * @param  $summaryFileName string The entity  summaryFileName field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateEventBillSummary($billSummaryId, $eventId, $title, $summary, $summaryFileName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventBillSummary($billSummaryId, $eventId, $title, $summary, $summaryFileName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates EventBillSummary item  details

     * @param  $billSummaryId int The entity  billSummaryId field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $summary string The entity  summary field 
     * @param  $summaryFileName string The entity  summaryFileName field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventBillSummaryDetails($billSummaryId, $eventId, $title, $summary, $summaryFileName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventBillSummaryDetails($billSummaryId, $eventId, $title, $summary, $summaryFileName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates eventId of the EventBillSummary entity
     * @param   $billSummaryId int The entity  billSummaryId field 
     * @param   $eventId int The entity  eventId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventBillSummaryEventId($billSummaryId, $eventId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventBillSummaryEventId($billSummaryId, $eventId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates title of the EventBillSummary entity
     * @param   $billSummaryId int The entity  billSummaryId field 
     * @param   $title string The entity  title field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventBillSummaryTitle($billSummaryId, $title) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventBillSummaryTitle($billSummaryId, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates summary of the EventBillSummary entity
     * @param   $billSummaryId int The entity  billSummaryId field 
     * @param   $summary string The entity  summary field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventBillSummarySummary($billSummaryId, $summary) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventBillSummarySummary($billSummaryId, $summary);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates summaryFileName of the EventBillSummary entity
     * @param   $billSummaryId int The entity  billSummaryId field 
     * @param   $summaryFileName string The entity  summaryFileName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventBillSummarySummaryFileName($billSummaryId, $summaryFileName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventBillSummarySummaryFileName($billSummaryId, $summaryFileName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the EventBillSummary item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventBillSummaryEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "eventId":
                    return $this->updateEventBillSummaryEventId($keyFieldValue, $newFieldValue);

                case "title":
                    return $this->updateEventBillSummaryTitle($keyFieldValue, $newFieldValue);

                case "summary":
                    return $this->updateEventBillSummarySummary($keyFieldValue, $newFieldValue);

                case "summaryFileName":
                    return $this->updateEventBillSummarySummaryFileName($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes EventBillSummary item
     * @param  $billSummaryId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteEventBillSummary($billSummaryId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteEventBillSummary($billSummaryId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected EventBillSummary items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedEventBillSummaries($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteEventBillSummary($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete EventBillSummary !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all EventBillSummary items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllEventBillSummaries() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllEventBillSummaries();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
