
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The EventVideoComment model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class EventVideoComment {

    private $videoCommentId;
    private $videoId;
    private $userId;
    private $commentText;
    private $date;

    /** Constructor of an EventVideoComment object
     *  @param $videoCommentId int The entity  primary key field 
     * @param  $videoId int The entity  videoId field 
     * @param  $userId int The entity  userId field 
     * @param  $commentText string The entity  commentText field 
     * @param  $date string The entity  date field 
     */
    function __construct($videoCommentId = "", $videoId = "", $userId = "", $commentText = "", $date = "") {
        $this->videoCommentId = $videoCommentId;
        $this->videoId = $videoId;
        $this->userId = $userId;
        $this->commentText = $commentText;
        $this->date = $date;
    }

    /**
     * Gets  $videoId value
     * @param $videoId
     * @return mixed
     */
    public function getVideoId() {
        return $this->videoId;
    }

    /**
     * Gets  $userId value
     * @param $userId
     * @return mixed
     */
    public function getUserId() {
        return $this->userId;
    }

    /**
     * Gets  $commentText value
     * @param $commentText
     * @return mixed
     */
    public function getCommentText() {
        return $this->commentText;
    }

    /**
     * Gets  $date value
     * @param $date
     * @return mixed
     */
    public function getDate() {
        return $this->date;
    }

    /**
     * Sets  $videoId value
     * @param $videoId
     * @return void
     */
    public function setVideoId($videoId) {
        $this->videoId = $videoId;
    }

    /**
     * Sets  $userId value
     * @param $userId
     * @return void
     */
    public function setUserId($userId) {
        $this->userId = $userId;
    }

    /**
     * Sets  $commentText value
     * @param $commentText
     * @return void
     */
    public function setCommentText($commentText) {
        $this->commentText = $commentText;
    }

    /**
     * Sets  $date value
     * @param $date
     * @return void
     */
    public function setDate($date) {
        $this->date = $date;
    }

    /**
     * Selects all EventVideoComment items
     * @return
     *   array The object having all EventVideoComment items
     *    or string with the Exception details if error occured
     */
    public function selectAllEventVideoComments() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllEventVideoComments();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets EventVideoComment item
     * @param $videoCommentId int  The table primary key
     * @return
     *   array The object with the given $videoCommentId value
     */
    public function getEventVideoCommentDetails($videoCommentId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectEventVideoCommentDetails($videoCommentId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new EventVideoComment entity
     * @param  $videoId int The entity  videoId field 
     * @param   $userId int The entity  userId field
     * @param   $commentText string The entity  commentText field
     * @param   $date string The entity  date field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewEventVideoComment($videoId, $userId, $commentText, $date) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewEventVideoComment($videoId, $userId, $commentText, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates EventVideoComment item
     * @param  $videoCommentId int The entity  videoCommentId field 
     * @param  $videoId int The entity  videoId field 
     * @param  $userId int The entity  userId field 
     * @param  $commentText string The entity  commentText field 
     * @param  $date string The entity  date field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoComment($videoCommentId, $videoId, $userId, $commentText, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoComment($videoCommentId, $videoId, $userId, $commentText, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates EventVideoComment item  details

     * @param  $videoCommentId int The entity  videoCommentId field 
     * @param  $videoId int The entity  videoId field 
     * @param  $userId int The entity  userId field 
     * @param  $commentText string The entity  commentText field 
     * @param  $date string The entity  date field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoCommentDetails($videoCommentId, $videoId, $userId, $commentText, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoCommentDetails($videoCommentId, $videoId, $userId, $commentText, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates videoId of the EventVideoComment entity
     * @param   $videoCommentId int The entity  videoCommentId field 
     * @param   $videoId int The entity  videoId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoCommentVideoId($videoCommentId, $videoId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoCommentVideoId($videoCommentId, $videoId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates userId of the EventVideoComment entity
     * @param   $videoCommentId int The entity  videoCommentId field 
     * @param   $userId int The entity  userId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoCommentUserId($videoCommentId, $userId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoCommentUserId($videoCommentId, $userId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates commentText of the EventVideoComment entity
     * @param   $videoCommentId int The entity  videoCommentId field 
     * @param   $commentText string The entity  commentText field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoCommentCommentText($videoCommentId, $commentText) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoCommentCommentText($videoCommentId, $commentText);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates date of the EventVideoComment entity
     * @param   $videoCommentId int The entity  videoCommentId field 
     * @param   $date string The entity  date field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoCommentDate($videoCommentId, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateEventVideoCommentDate($videoCommentId, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the EventVideoComment item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateEventVideoCommentEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "videoId":
                    return $this->updateEventVideoCommentVideoId($keyFieldValue, $newFieldValue);

                case "userId":
                    return $this->updateEventVideoCommentUserId($keyFieldValue, $newFieldValue);

                case "commentText":
                    return $this->updateEventVideoCommentCommentText($keyFieldValue, $newFieldValue);

                case "date":
                    return $this->updateEventVideoCommentDate($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes EventVideoComment item
     * @param  $videoCommentId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteEventVideoComment($videoCommentId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteEventVideoComment($videoCommentId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected EventVideoComment items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedEventVideoComments($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteEventVideoComment($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete EventVideoComment !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all EventVideoComment items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllEventVideoComments() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllEventVideoComments();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
