
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The Expense model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class Expense {

    private $expenseId;
    private $eventId;
    private $title;
    private $amount;
    private $category;
    private $billFileName;
    private $transactionDate;

    /** Constructor of an Expense object
     *  @param $expenseId int The entity  primary key field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $amount double The entity  amount field 
     * @param  $category string The entity  category field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $transactionDate string The entity  transactionDate field 
     */
    function __construct($expenseId = "", $eventId = "", $title = "", $amount = "", $category = "", $billFileName = "", $transactionDate = "") {
        $this->expenseId = $expenseId;
        $this->eventId = $eventId;
        $this->title = $title;
        $this->amount = $amount;
        $this->category = $category;
        $this->billFileName = $billFileName;
        $this->transactionDate = $transactionDate;
    }

    /**
     * Gets  $eventId value
     * @param $eventId
     * @return mixed
     */
    public function getEventId() {
        return $this->eventId;
    }

    /**
     * Gets  $title value
     * @param $title
     * @return mixed
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Gets  $amount value
     * @param $amount
     * @return mixed
     */
    public function getAmount() {
        return $this->amount;
    }

    /**
     * Gets  $category value
     * @param $category
     * @return mixed
     */
    public function getCategory() {
        return $this->category;
    }

    /**
     * Gets  $billFileName value
     * @param $billFileName
     * @return mixed
     */
    public function getBillFileName() {
        return $this->billFileName;
    }

    /**
     * Gets  $transactionDate value
     * @param $transactionDate
     * @return mixed
     */
    public function getTransactionDate() {
        return $this->transactionDate;
    }

    /**
     * Sets  $eventId value
     * @param $eventId
     * @return void
     */
    public function setEventId($eventId) {
        $this->eventId = $eventId;
    }

    /**
     * Sets  $title value
     * @param $title
     * @return void
     */
    public function setTitle($title) {
        $this->title = $title;
    }

    /**
     * Sets  $amount value
     * @param $amount
     * @return void
     */
    public function setAmount($amount) {
        $this->amount = $amount;
    }

    /**
     * Sets  $category value
     * @param $category
     * @return void
     */
    public function setCategory($category) {
        $this->category = $category;
    }

    /**
     * Sets  $billFileName value
     * @param $billFileName
     * @return void
     */
    public function setBillFileName($billFileName) {
        $this->billFileName = $billFileName;
    }

    /**
     * Sets  $transactionDate value
     * @param $transactionDate
     * @return void
     */
    public function setTransactionDate($transactionDate) {
        $this->transactionDate = $transactionDate;
    }

    /**
     * Selects all Expense items
     * @return
     *   array The object having all Expense items
     *    or string with the Exception details if error occured
     */
    public function selectAllExpenses() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllExpenses();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets Expense item
     * @param $expenseId int  The table primary key
     * @return
     *   array The object with the given $expenseId value
     */
    public function getExpenseDetails($expenseId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectExpenseDetails($expenseId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new Expense entity
     * @param  $eventId int The entity  eventId field 
     * @param   $title string The entity  title field
     * @param   $amount double The entity  amount field
     * @param   $category string The entity  category field
     * @param   $billFileName string The entity  billFileName field
     * @param   $transactionDate string The entity  transactionDate field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewExpense($eventId, $title, $amount, $category, $billFileName, $transactionDate) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewExpense($eventId, $title, $amount, $category, $billFileName, $transactionDate);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Expense item
     * @param  $expenseId int The entity  expenseId field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $amount double The entity  amount field 
     * @param  $category string The entity  category field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $transactionDate string The entity  transactionDate field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateExpense($expenseId, $eventId, $title, $amount, $category, $billFileName, $transactionDate) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateExpense($expenseId, $eventId, $title, $amount, $category, $billFileName, $transactionDate);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Expense item  details

     * @param  $expenseId int The entity  expenseId field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $amount double The entity  amount field 
     * @param  $category string The entity  category field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $transactionDate string The entity  transactionDate field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateExpenseDetails($expenseId, $eventId, $title, $amount, $category, $billFileName, $transactionDate) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateExpenseDetails($expenseId, $eventId, $title, $amount, $category, $billFileName, $transactionDate);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates eventId of the Expense entity
     * @param   $expenseId int The entity  expenseId field 
     * @param   $eventId int The entity  eventId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateExpenseEventId($expenseId, $eventId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateExpenseEventId($expenseId, $eventId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates title of the Expense entity
     * @param   $expenseId int The entity  expenseId field 
     * @param   $title string The entity  title field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateExpenseTitle($expenseId, $title) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateExpenseTitle($expenseId, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates amount of the Expense entity
     * @param   $expenseId int The entity  expenseId field 
     * @param   $amount double The entity  amount field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateExpenseAmount($expenseId, $amount) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateExpenseAmount($expenseId, $amount);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates category of the Expense entity
     * @param   $expenseId int The entity  expenseId field 
     * @param   $category string The entity  category field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateExpenseCategory($expenseId, $category) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateExpenseCategory($expenseId, $category);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates billFileName of the Expense entity
     * @param   $expenseId int The entity  expenseId field 
     * @param   $billFileName string The entity  billFileName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateExpenseBillFileName($expenseId, $billFileName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateExpenseBillFileName($expenseId, $billFileName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates transactionDate of the Expense entity
     * @param   $expenseId int The entity  expenseId field 
     * @param   $transactionDate string The entity  transactionDate field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateExpenseTransactionDate($expenseId, $transactionDate) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateExpenseTransactionDate($expenseId, $transactionDate);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the Expense item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateExpenseEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "eventId":
                    return $this->updateExpenseEventId($keyFieldValue, $newFieldValue);

                case "title":
                    return $this->updateExpenseTitle($keyFieldValue, $newFieldValue);

                case "amount":
                    return $this->updateExpenseAmount($keyFieldValue, $newFieldValue);

                case "category":
                    return $this->updateExpenseCategory($keyFieldValue, $newFieldValue);

                case "billFileName":
                    return $this->updateExpenseBillFileName($keyFieldValue, $newFieldValue);

                case "transactionDate":
                    return $this->updateExpenseTransactionDate($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes Expense item
     * @param  $expenseId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteExpense($expenseId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteExpense($expenseId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected Expense items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedExpenses($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteExpense($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete Expense !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all Expense items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllExpenses() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllExpenses();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }
    
    /**
     * Selects all Expense items by year
     * @return
     *   array The object having all Expense items
     *    or string with the Exception details if error occured
     */
    public function selectAllExpensesByYear() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllExpensesByYear();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
