
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The Income model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class Income {

    private $incomeId;
    private $eventId;
    private $title;
    private $amount;
    private $category;
    private $billFileName;
    private $transactionDate;

    /** Constructor of an Income object
     *  @param $incomeId int The entity  primary key field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $amount double The entity  amount field 
     * @param  $category string The entity  category field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $transactionDate string The entity  transactionDate field 
     */
    function __construct($incomeId = "", $eventId = "", $title = "", $amount = "", 
            $category = "", $billFileName = "", $transactionDate = "") {
        $this->incomeId = $incomeId;
        $this->eventId = $eventId;
        $this->title = $title;
        $this->amount = $amount;
        $this->category = $category;
        $this->billFileName = $billFileName;
        $this->transactionDate = $transactionDate;
    }

    /**
     * Gets  $eventId value
     * @param $eventId
     * @return mixed
     */
    public function getEventId() {
        return $this->eventId;
    }

    /**
     * Gets  $title value
     * @param $title
     * @return mixed
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Gets  $amount value
     * @param $amount
     * @return mixed
     */
    public function getAmount() {
        return $this->amount;
    }

    /**
     * Gets  $category value
     * @param $category
     * @return mixed
     */
    public function getCategory() {
        return $this->category;
    }

    /**
     * Gets  $billFileName value
     * @param $billFileName
     * @return mixed
     */
    public function getBillFileName() {
        return $this->billFileName;
    }

    /**
     * Gets  $transactionDate value
     * @param $transactionDate
     * @return mixed
     */
    public function getTransactionDate() {
        return $this->transactionDate;
    }

    /**
     * Sets  $eventId value
     * @param $eventId
     * @return void
     */
    public function setEventId($eventId) {
        $this->eventId = $eventId;
    }

    /**
     * Sets  $title value
     * @param $title
     * @return void
     */
    public function setTitle($title) {
        $this->title = $title;
    }

    /**
     * Sets  $amount value
     * @param $amount
     * @return void
     */
    public function setAmount($amount) {
        $this->amount = $amount;
    }

    /**
     * Sets  $category value
     * @param $category
     * @return void
     */
    public function setCategory($category) {
        $this->category = $category;
    }

    /**
     * Sets  $billFileName value
     * @param $billFileName
     * @return void
     */
    public function setBillFileName($billFileName) {
        $this->billFileName = $billFileName;
    }

    /**
     * Sets  $transactionDate value
     * @param $transactionDate
     * @return void
     */
    public function setTransactionDate($transactionDate) {
        $this->transactionDate = $transactionDate;
    }

    /**
     * Selects all Income items
     * @return
     *   array The object having all Income items
     *    or string with the Exception details if error occured
     */
    public function selectAllIncomes() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllIncomes();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets Income item
     * @param $incomeId int  The table primary key
     * @return
     *   array The object with the given $incomeId value
     */
    public function getIncomeDetails($incomeId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectIncomeDetails($incomeId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new Income entity
     * @param  $eventId int The entity  eventId field 
     * @param   $title string The entity  title field
     * @param   $amount double The entity  amount field
     * @param   $category string The entity  category field
     * @param   $billFileName string The entity  billFileName field
     * @param   $transactionDate string The entity  transactionDate field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewIncome($eventId, $title, $amount, $category, $billFileName, $transactionDate) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewIncome($eventId, $title, $amount, $category, $billFileName, $transactionDate);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Income item
     * @param  $incomeId int The entity  incomeId field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $amount double The entity  amount field 
     * @param  $category string The entity  category field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $transactionDate string The entity  transactionDate field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateIncome($incomeId, $eventId, $title, $amount, $category, $billFileName, $transactionDate) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateIncome($incomeId, $eventId, $title, $amount, $category, $billFileName, $transactionDate);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Income item  details

     * @param  $incomeId int The entity  incomeId field 
     * @param  $eventId int The entity  eventId field 
     * @param  $title string The entity  title field 
     * @param  $amount double The entity  amount field 
     * @param  $category string The entity  category field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $transactionDate string The entity  transactionDate field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateIncomeDetails($incomeId, $eventId, $title, $amount, $category, $billFileName, $transactionDate) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateIncomeDetails($incomeId, $eventId, $title, $amount, $category, $billFileName, $transactionDate);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates eventId of the Income entity
     * @param   $incomeId int The entity  incomeId field 
     * @param   $eventId int The entity  eventId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateIncomeEventId($incomeId, $eventId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateIncomeEventId($incomeId, $eventId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates title of the Income entity
     * @param   $incomeId int The entity  incomeId field 
     * @param   $title string The entity  title field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateIncomeTitle($incomeId, $title) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateIncomeTitle($incomeId, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates amount of the Income entity
     * @param   $incomeId int The entity  incomeId field 
     * @param   $amount double The entity  amount field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateIncomeAmount($incomeId, $amount) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateIncomeAmount($incomeId, $amount);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates category of the Income entity
     * @param   $incomeId int The entity  incomeId field 
     * @param   $category string The entity  category field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateIncomeCategory($incomeId, $category) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateIncomeCategory($incomeId, $category);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates billFileName of the Income entity
     * @param   $incomeId int The entity  incomeId field 
     * @param   $billFileName string The entity  billFileName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateIncomeBillFileName($incomeId, $billFileName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateIncomeBillFileName($incomeId, $billFileName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates transactionDate of the Income entity
     * @param   $incomeId int The entity  incomeId field 
     * @param   $transactionDate string The entity  transactionDate field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateIncomeTransactionDate($incomeId, $transactionDate) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateIncomeTransactionDate($incomeId, $transactionDate);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the Income item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateIncomeEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "eventId":
                    return $this->updateIncomeEventId($keyFieldValue, $newFieldValue);

                case "title":
                    return $this->updateIncomeTitle($keyFieldValue, $newFieldValue);

                case "amount":
                    return $this->updateIncomeAmount($keyFieldValue, $newFieldValue);

                case "category":
                    return $this->updateIncomeCategory($keyFieldValue, $newFieldValue);

                case "billFileName":
                    return $this->updateIncomeBillFileName($keyFieldValue, $newFieldValue);

                case "transactionDate":
                    return $this->updateIncomeTransactionDate($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes Income item
     * @param  $incomeId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteIncome($incomeId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteIncome($incomeId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected Income items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedIncomes($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteIncome($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete Income !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all Income items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllIncomes() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllIncomes();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }
    
    /**
     * Selects all Income items by year
     * @return
     *   array The object having all Income items
     *    or string with the Exception details if error occured
     */
    public function selectAllIncomesByYear() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllIncomesByYear();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
