
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The MemberFee model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class MemberFee {

    private $memberFeeId;
    private $memberId;
    private $amount;
    private $billFileName;
    private $date;

    /** Constructor of an MemberFee object
     *  @param $memberFeeId int The entity  primary key field 
     * @param  $memberId int The entity  memberId field 
     * @param  $amount double The entity  amount field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $date string The entity  date field 
     */
    function __construct($memberFeeId = "", $memberId = "", $amount = "", $billFileName = "", $date = "") {
        $this->memberFeeId = $memberFeeId;
        $this->memberId = $memberId;
        $this->amount = $amount;
        $this->billFileName = $billFileName;
        $this->date = $date;
    }

    /**
     * Gets  $memberId value
     * @param $memberId
     * @return mixed
     */
    public function getMemberId() {
        return $this->memberId;
    }

    /**
     * Gets  $amount value
     * @param $amount
     * @return mixed
     */
    public function getAmount() {
        return $this->amount;
    }

    /**
     * Gets  $billFileName value
     * @param $billFileName
     * @return mixed
     */
    public function getBillFileName() {
        return $this->billFileName;
    }

    /**
     * Gets  $date value
     * @param $date
     * @return mixed
     */
    public function getDate() {
        return $this->date;
    }

    /**
     * Sets  $memberId value
     * @param $memberId
     * @return void
     */
    public function setMemberId($memberId) {
        $this->memberId = $memberId;
    }

    /**
     * Sets  $amount value
     * @param $amount
     * @return void
     */
    public function setAmount($amount) {
        $this->amount = $amount;
    }

    /**
     * Sets  $billFileName value
     * @param $billFileName
     * @return void
     */
    public function setBillFileName($billFileName) {
        $this->billFileName = $billFileName;
    }

    /**
     * Sets  $date value
     * @param $date
     * @return void
     */
    public function setDate($date) {
        $this->date = $date;
    }

    /**
     * Selects all MemberFee items
     * @return
     *   array The object having all MemberFee items
     *    or string with the Exception details if error occured
     */
    public function selectAllMemberFees() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllMemberFees();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets MemberFee item
     * @param $memberFeeId int  The table primary key
     * @return
     *   array The object with the given $memberFeeId value
     */
    public function getMemberFeeDetails($memberFeeId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectMemberFeeDetails($memberFeeId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new MemberFee entity
     * @param  $memberId int The entity  memberId field 
     * @param   $amount double The entity  amount field
     * @param   $billFileName string The entity  billFileName field
     * @param   $date string The entity  date field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewMemberFee($memberId, $amount, $billFileName, $date) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewMemberFee($memberId, $amount, $billFileName, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates MemberFee item
     * @param  $memberFeeId int The entity  memberFeeId field 
     * @param  $memberId int The entity  memberId field 
     * @param  $amount double The entity  amount field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $date string The entity  date field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateMemberFee($memberFeeId, $memberId, $amount, $billFileName, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateMemberFee($memberFeeId, $memberId, $amount, $billFileName, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates MemberFee item  details

     * @param  $memberFeeId int The entity  memberFeeId field 
     * @param  $memberId int The entity  memberId field 
     * @param  $amount double The entity  amount field 
     * @param  $billFileName string The entity  billFileName field 
     * @param  $date string The entity  date field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateMemberFeeDetails($memberFeeId, $memberId, $amount, $billFileName, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateMemberFeeDetails($memberFeeId, $memberId, $amount, $billFileName, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates memberId of the MemberFee entity
     * @param   $memberFeeId int The entity  memberFeeId field 
     * @param   $memberId int The entity  memberId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateMemberFeeMemberId($memberFeeId, $memberId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateMemberFeeMemberId($memberFeeId, $memberId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates amount of the MemberFee entity
     * @param   $memberFeeId int The entity  memberFeeId field 
     * @param   $amount double The entity  amount field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateMemberFeeAmount($memberFeeId, $amount) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateMemberFeeAmount($memberFeeId, $amount);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates billFileName of the MemberFee entity
     * @param   $memberFeeId int The entity  memberFeeId field 
     * @param   $billFileName string The entity  billFileName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateMemberFeeBillFileName($memberFeeId, $billFileName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateMemberFeeBillFileName($memberFeeId, $billFileName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates date of the MemberFee entity
     * @param   $memberFeeId int The entity  memberFeeId field 
     * @param   $date string The entity  date field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateMemberFeeDate($memberFeeId, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateMemberFeeDate($memberFeeId, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the MemberFee item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateMemberFeeEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "memberId":
                    return $this->updateMemberFeeMemberId($keyFieldValue, $newFieldValue);

                case "amount":
                    return $this->updateMemberFeeAmount($keyFieldValue, $newFieldValue);

                case "billFileName":
                    return $this->updateMemberFeeBillFileName($keyFieldValue, $newFieldValue);

                case "date":
                    return $this->updateMemberFeeDate($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes MemberFee item
     * @param  $memberFeeId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteMemberFee($memberFeeId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteMemberFee($memberFeeId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected MemberFee items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedMemberFees($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteMemberFee($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete MemberFee !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all MemberFee items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllMemberFees() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllMemberFees();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
