
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The OfficeMember model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class OfficeMember {

    private $officeMemberId;
    private $memberId;
    private $position;

    /** Constructor of an OfficeMember object
     *  @param $officeMemberId int The entity  primary key field 
     * @param  $memberId int The entity  memberId field 
     * @param  $position string The entity  position field 
     */
    function __construct($officeMemberId = "", $memberId = "", $position = "") {
        $this->officeMemberId = $officeMemberId;
        $this->memberId = $memberId;
        $this->position = $position;
    }

    /**
     * Gets  $memberId value
     * @param $memberId
     * @return mixed
     */
    public function getMemberId() {
        return $this->memberId;
    }

    /**
     * Gets  $position value
     * @param $position
     * @return mixed
     */
    public function getPosition() {
        return $this->position;
    }

    /**
     * Sets  $memberId value
     * @param $memberId
     * @return void
     */
    public function setMemberId($memberId) {
        $this->memberId = $memberId;
    }

    /**
     * Sets  $position value
     * @param $position
     * @return void
     */
    public function setPosition($position) {
        $this->position = $position;
    }

    /**
     * Selects all OfficeMember items
     * @return
     *   array The object having all OfficeMember items
     *    or string with the Exception details if error occured
     */
    public function selectAllOfficeMembers() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllOfficeMembers();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets OfficeMember item
     * @param $officeMemberId int  The table primary key
     * @return
     *   array The object with the given $officeMemberId value
     */
    public function getOfficeMemberDetails($officeMemberId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectOfficeMemberDetails($officeMemberId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new OfficeMember entity
     * @param  $memberId int The entity  memberId field 
     * @param   $position string The entity  position field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewOfficeMember($memberId, $position) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewOfficeMember($memberId, $position);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates OfficeMember item
     * @param  $officeMemberId int The entity  officeMemberId field 
     * @param  $memberId int The entity  memberId field 
     * @param  $position string The entity  position field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateOfficeMember($officeMemberId, $memberId, $position) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOfficeMember($officeMemberId, $memberId, $position);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates OfficeMember item  details

     * @param  $officeMemberId int The entity  officeMemberId field 
     * @param  $memberId int The entity  memberId field 
     * @param  $position string The entity  position field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOfficeMemberDetails($officeMemberId, $memberId, $position) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOfficeMemberDetails($officeMemberId, $memberId, $position);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates memberId of the OfficeMember entity
     * @param   $officeMemberId int The entity  officeMemberId field 
     * @param   $memberId int The entity  memberId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOfficeMemberMemberId($officeMemberId, $memberId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOfficeMemberMemberId($officeMemberId, $memberId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates position of the OfficeMember entity
     * @param   $officeMemberId int The entity  officeMemberId field 
     * @param   $position string The entity  position field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOfficeMemberPosition($officeMemberId, $position) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOfficeMemberPosition($officeMemberId, $position);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the OfficeMember item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOfficeMemberEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "memberId":
                    return $this->updateOfficeMemberMemberId($keyFieldValue, $newFieldValue);

                case "position":
                    return $this->updateOfficeMemberPosition($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes OfficeMember item
     * @param  $officeMemberId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteOfficeMember($officeMemberId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteOfficeMember($officeMemberId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected OfficeMember items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedOfficeMembers($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteOfficeMember($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete OfficeMember !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all OfficeMember items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllOfficeMembers() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllOfficeMembers();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
