
<?php
/**
 * This module was auto generated by the G-Watcho module generator
 * The OldExam model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class OldExam {

    private $examId;
    private $userId;
    private $subject;
    private $title;
    private $semester;
    private $date;
    private $fileFullName;

    /** Constructor of an OldExam object
     *  @param $examId int The entity  primary key field 
     * @param  $userId int The entity  userId field 
     * @param  $subject string The entity  subject field 
     * @param  $title string The entity  title field 
     * @param  $semester string The entity  semester field 
     * @param  $date string The entity  date field 
     * @param  $fileFullName string The entity  fileFullName field 
     */
    function __construct($examId = "", $userId = "", $subject = "", $title = "", $semester = "", $date = "", $fileFullName = "") {
        $this->examId = $examId;
        $this->userId = $userId;
        $this->subject = $subject;
        $this->title = $title;
        $this->semester = $semester;
        $this->date = $date;
        $this->fileFullName = $fileFullName;
    }

    /**
     * Gets  $userId value
     * @param $userId
     * @return mixed
     */
    public function getUserId() {
        return $this->userId;
    }

    /**
     * Gets  $subject value
     * @param $subject
     * @return mixed
     */
    public function getSubject() {
        return $this->subject;
    }

    /**
     * Gets  $title value
     * @param $title
     * @return mixed
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Gets  $semester value
     * @param $semester
     * @return mixed
     */
    public function getSemester() {
        return $this->semester;
    }

    /**
     * Gets  $date value
     * @param $date
     * @return mixed
     */
    public function getDate() {
        return $this->date;
    }

    /**
     * Gets  $fileFullName value
     * @param $fileFullName
     * @return mixed
     */
    public function getFileFullName() {
        return $this->fileFullName;
    }

    /**
     * Sets  $userId value
     * @param $userId
     * @return void
     */
    public function setUserId($userId) {
        $this->userId = $userId;
    }

    /**
     * Sets  $subject value
     * @param $subject
     * @return void
     */
    public function setSubject($subject) {
        $this->subject = $subject;
    }

    /**
     * Sets  $title value
     * @param $title
     * @return void
     */
    public function setTitle($title) {
        $this->title = $title;
    }

    /**
     * Sets  $semester value
     * @param $semester
     * @return void
     */
    public function setSemester($semester) {
        $this->semester = $semester;
    }

    /**
     * Sets  $date value
     * @param $date
     * @return void
     */
    public function setDate($date) {
        $this->date = $date;
    }

    /**
     * Sets  $fileFullName value
     * @param $fileFullName
     * @return void
     */
    public function setFileFullName($fileFullName) {
        $this->fileFullName = $fileFullName;
    }

    /**
     * Selects all OldExam items
     * @return
     *   array The object having all OldExam items
     *    or string with the Exception details if error occured
     */
    public function selectAllOldExams() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllOldExams();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets OldExam item
     * @param $examId int  The table primary key
     * @return
     *   array The object with the given $examId value
     */
    public function getOldExamDetails($examId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectOldExamDetails($examId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new OldExam entity
     * @param  $userId int The entity  userId field 
     * @param   $subject string The entity  subject field
     * @param   $title string The entity  title field
     * @param   $semester string The entity  semester field
     * @param   $date string The entity  date field
     * @param   $fileFullName string The entity  fileFullName field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewOldExam($userId, $subject, $title, $semester, $date, $fileFullName) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewOldExam($userId, $subject, $title, $semester, $date, $fileFullName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates OldExam item
     * @param  $examId int The entity  examId field 
     * @param  $userId int The entity  userId field 
     * @param  $subject string The entity  subject field 
     * @param  $title string The entity  title field 
     * @param  $semester string The entity  semester field 
     * @param  $date string The entity  date field 
     * @param  $fileFullName string The entity  fileFullName field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateOldExam($examId, $userId, $subject, $title, $semester, $date, $fileFullName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOldExam($examId, $userId, $subject, $title, $semester, $date, $fileFullName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates OldExam item  details

     * @param  $examId int The entity  examId field 
     * @param  $userId int The entity  userId field 
     * @param  $subject string The entity  subject field 
     * @param  $title string The entity  title field 
     * @param  $semester string The entity  semester field 
     * @param  $date string The entity  date field 
     * @param  $fileFullName string The entity  fileFullName field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOldExamDetails($examId, $userId, $subject, $title, $semester, $date, $fileFullName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOldExamDetails($examId, $userId, $subject, $title, $semester, $date, $fileFullName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates userId of the OldExam entity
     * @param   $examId int The entity  examId field 
     * @param   $userId int The entity  userId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOldExamUserId($examId, $userId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOldExamUserId($examId, $userId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates subject of the OldExam entity
     * @param   $examId int The entity  examId field 
     * @param   $subject string The entity  subject field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOldExamSubject($examId, $subject) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOldExamSubject($examId, $subject);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates title of the OldExam entity
     * @param   $examId int The entity  examId field 
     * @param   $title string The entity  title field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOldExamTitle($examId, $title) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOldExamTitle($examId, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates semester of the OldExam entity
     * @param   $examId int The entity  examId field 
     * @param   $semester string The entity  semester field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOldExamSemester($examId, $semester) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOldExamSemester($examId, $semester);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates date of the OldExam entity
     * @param   $examId int The entity  examId field 
     * @param   $date string The entity  date field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOldExamDate($examId, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOldExamDate($examId, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates fileFullName of the OldExam entity
     * @param   $examId int The entity  examId field 
     * @param   $fileFullName string The entity  fileFullName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOldExamFileFullName($examId, $fileFullName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateOldExamFileFullName($examId, $fileFullName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the OldExam item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateOldExamEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "userId":
                    return $this->updateOldExamUserId($keyFieldValue, $newFieldValue);

                case "subject":
                    return $this->updateOldExamSubject($keyFieldValue, $newFieldValue);

                case "title":
                    return $this->updateOldExamTitle($keyFieldValue, $newFieldValue);

                case "semester":
                    return $this->updateOldExamSemester($keyFieldValue, $newFieldValue);

                case "date":
                    return $this->updateOldExamDate($keyFieldValue, $newFieldValue);

                case "fileFullName":
                    return $this->updateOldExamFileFullName($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes OldExam item
     * @param  $examId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteOldExam($examId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteOldExam($examId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected OldExam items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedOldExams($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteOldExam($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete OldExam !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all OldExam items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllOldExams() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllOldExams();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
