
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The Project model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class Project {

    private $projectId;
    private $userId;
    private $title;
    private $summary;

    /** Constructor of an Project object
     *  @param $projectId int The entity  primary key field 
     * @param  $userId int The entity  userId field 
     * @param  $title string The entity  title field 
     * @param  $summary string The entity  summary field 
     */
    function __construct($projectId = "", $userId = "", $title = "", $summary = "") {
        $this->projectId = $projectId;
        $this->userId = $userId;
        $this->title = $title;
        $this->summary = $summary;
    }

    /**
     * Gets  $userId value
     * @param $userId
     * @return mixed
     */
    public function getUserId() {
        return $this->userId;
    }

    /**
     * Gets  $title value
     * @param $title
     * @return mixed
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Gets  $summary value
     * @param $summary
     * @return mixed
     */
    public function getSummary() {
        return $this->summary;
    }

    /**
     * Sets  $userId value
     * @param $userId
     * @return void
     */
    public function setUserId($userId) {
        $this->userId = $userId;
    }

    /**
     * Sets  $title value
     * @param $title
     * @return void
     */
    public function setTitle($title) {
        $this->title = $title;
    }

    /**
     * Sets  $summary value
     * @param $summary
     * @return void
     */
    public function setSummary($summary) {
        $this->summary = $summary;
    }

    /**
     * Selects all Project items
     * @return
     *   array The object having all Project items
     *    or string with the Exception details if error occured
     */
    public function selectAllProjects() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllProjects();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets Project item
     * @param $projectId int  The table primary key
     * @return
     *   array The object with the given $projectId value
     */
    public function getProjectDetails($projectId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectProjectDetails($projectId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new Project entity
     * @param  $userId int The entity  userId field 
     * @param   $title string The entity  title field
     * @param   $summary string The entity  summary field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewProject($userId, $title, $summary) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewProject($userId, $title, $summary);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Project item
     * @param  $projectId int The entity  projectId field 
     * @param  $userId int The entity  userId field 
     * @param  $title string The entity  title field 
     * @param  $summary string The entity  summary field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateProject($projectId, $userId, $title, $summary) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateProject($projectId, $userId, $title, $summary);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Project item  details

     * @param  $projectId int The entity  projectId field 
     * @param  $userId int The entity  userId field 
     * @param  $title string The entity  title field 
     * @param  $summary string The entity  summary field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateProjectDetails($projectId, $userId, $title, $summary) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateProjectDetails($projectId, $userId, $title, $summary);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates userId of the Project entity
     * @param   $projectId int The entity  projectId field 
     * @param   $userId int The entity  userId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateProjectUserId($projectId, $userId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateProjectUserId($projectId, $userId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates title of the Project entity
     * @param   $projectId int The entity  projectId field 
     * @param   $title string The entity  title field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateProjectTitle($projectId, $title) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateProjectTitle($projectId, $title);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates summary of the Project entity
     * @param   $projectId int The entity  projectId field 
     * @param   $summary string The entity  summary field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateProjectSummary($projectId, $summary) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateProjectSummary($projectId, $summary);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the Project item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateProjectEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "userId":
                    return $this->updateProjectUserId($keyFieldValue, $newFieldValue);

                case "title":
                    return $this->updateProjectTitle($keyFieldValue, $newFieldValue);

                case "summary":
                    return $this->updateProjectSummary($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes Project item
     * @param  $projectId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteProject($projectId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteProject($projectId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected Project items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedProjects($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteProject($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete Project !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all Project items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllProjects() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllProjects();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
