
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The Publication model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class Publication {

    private $publicationId;
    private $userId;
    private $category;
    private $summary;
    private $date;

    /** Constructor of an Publication object
     *  @param $publicationId int The entity  primary key field 
     * @param  $userId int The entity  userId field 
     * @param  $category string The entity  category field 
     * @param  $summary string The entity  summary field 
     * @param  $date string The entity  date field 
     */
    function __construct($publicationId = "", $userId = "", $category = "", $summary = "", $date = "") {
        $this->publicationId = $publicationId;
        $this->userId = $userId;
        $this->category = $category;
        $this->summary = $summary;
        $this->date = $date;
    }

    /**
     * Gets  $userId value
     * @param $userId
     * @return mixed
     */
    public function getUserId() {
        return $this->userId;
    }

    /**
     * Gets  $category value
     * @param $category
     * @return mixed
     */
    public function getCategory() {
        return $this->category;
    }

    /**
     * Gets  $summary value
     * @param $summary
     * @return mixed
     */
    public function getSummary() {
        return $this->summary;
    }

    /**
     * Gets  $date value
     * @param $date
     * @return mixed
     */
    public function getDate() {
        return $this->date;
    }

    /**
     * Sets  $userId value
     * @param $userId
     * @return void
     */
    public function setUserId($userId) {
        $this->userId = $userId;
    }

    /**
     * Sets  $category value
     * @param $category
     * @return void
     */
    public function setCategory($category) {
        $this->category = $category;
    }

    /**
     * Sets  $summary value
     * @param $summary
     * @return void
     */
    public function setSummary($summary) {
        $this->summary = $summary;
    }

    /**
     * Sets  $date value
     * @param $date
     * @return void
     */
    public function setDate($date) {
        $this->date = $date;
    }

    /**
     * Selects all Publication items
     * @return
     *   array The object having all Publication items
     *    or string with the Exception details if error occured
     */
    public function selectAllPublications() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllPublications();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets Publication item
     * @param $publicationId int  The table primary key
     * @return
     *   array The object with the given $publicationId value
     */
    public function getPublicationDetails($publicationId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectPublicationDetails($publicationId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new Publication entity
     * @param  $userId int The entity  userId field 
     * @param   $category string The entity  category field
     * @param   $summary string The entity  summary field
     * @param   $date string The entity  date field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewPublication($userId, $category, $summary, $date) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewPublication($userId, $category, $summary, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Publication item
     * @param  $publicationId int The entity  publicationId field 
     * @param  $userId int The entity  userId field 
     * @param  $category string The entity  category field 
     * @param  $summary string The entity  summary field 
     * @param  $date string The entity  date field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updatePublication($publicationId, $userId, $category, $summary, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updatePublication($publicationId, $userId, $category, $summary, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Publication item  details

     * @param  $publicationId int The entity  publicationId field 
     * @param  $userId int The entity  userId field 
     * @param  $category string The entity  category field 
     * @param  $summary string The entity  summary field 
     * @param  $date string The entity  date field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updatePublicationDetails($publicationId, $userId, $category, $summary, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updatePublicationDetails($publicationId, $userId, $category, $summary, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates userId of the Publication entity
     * @param   $publicationId int The entity  publicationId field 
     * @param   $userId int The entity  userId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updatePublicationUserId($publicationId, $userId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updatePublicationUserId($publicationId, $userId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates category of the Publication entity
     * @param   $publicationId int The entity  publicationId field 
     * @param   $category string The entity  category field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updatePublicationCategory($publicationId, $category) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updatePublicationCategory($publicationId, $category);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates summary of the Publication entity
     * @param   $publicationId int The entity  publicationId field 
     * @param   $summary string The entity  summary field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updatePublicationSummary($publicationId, $summary) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updatePublicationSummary($publicationId, $summary);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates date of the Publication entity
     * @param   $publicationId int The entity  publicationId field 
     * @param   $date string The entity  date field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updatePublicationDate($publicationId, $date) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updatePublicationDate($publicationId, $date);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the Publication item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updatePublicationEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "userId":
                    return $this->updatePublicationUserId($keyFieldValue, $newFieldValue);

                case "category":
                    return $this->updatePublicationCategory($keyFieldValue, $newFieldValue);

                case "summary":
                    return $this->updatePublicationSummary($keyFieldValue, $newFieldValue);

                case "date":
                    return $this->updatePublicationDate($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes Publication item
     * @param  $publicationId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deletePublication($publicationId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deletePublication($publicationId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected Publication items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedPublications($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deletePublication($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete Publication !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all Publication items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllPublications() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllPublications();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
