
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The UserProfile model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class UserProfile {

    private $profileId;
    private $userId;
    private $photoFileName;
    private $defalutLanguage;

    /** Constructor of an UserProfile object
     *  @param $profileId int The entity  primary key field 
     * @param  $userId int The entity  userId field 
     * @param  $photoFileName string The entity  photoFileName field 
     * @param  $defalutLanguage string The entity  defalutLanguage field 
     */
    function __construct($profileId = "", $userId = "", $photoFileName = "", $defalutLanguage = "") {
        $this->profileId = $profileId;
        $this->userId = $userId;
        $this->photoFileName = $photoFileName;
        $this->defalutLanguage = $defalutLanguage;
    }

    /**
     * Gets  $userId value
     * @param $userId
     * @return mixed
     */
    public function getUserId() {
        return $this->userId;
    }

    /**
     * Gets  $photoFileName value
     * @param $photoFileName
     * @return mixed
     */
    public function getPhotoFileName() {
        return $this->photoFileName;
    }

    /**
     * Gets  $defalutLanguage value
     * @param $defalutLanguage
     * @return mixed
     */
    public function getDefalutLanguage() {
        return $this->defalutLanguage;
    }

    /**
     * Sets  $userId value
     * @param $userId
     * @return void
     */
    public function setUserId($userId) {
        $this->userId = $userId;
    }

    /**
     * Sets  $photoFileName value
     * @param $photoFileName
     * @return void
     */
    public function setPhotoFileName($photoFileName) {
        $this->photoFileName = $photoFileName;
    }

    /**
     * Sets  $defalutLanguage value
     * @param $defalutLanguage
     * @return void
     */
    public function setDefalutLanguage($defalutLanguage) {
        $this->defalutLanguage = $defalutLanguage;
    }

    /**
     * Selects all UserProfile items
     * @return
     *   array The object having all UserProfile items
     *    or string with the Exception details if error occured
     */
    public function selectAllUserProfiles() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllUserProfiles();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets UserProfile item
     * @param $profileId int  The table primary key
     * @return
     *   array The object with the given $profileId value
     */
    public function getUserProfileDetails($profileId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectUserProfileDetails($profileId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new UserProfile entity
     * @param  $userId int The entity  userId field 
     * @param   $photoFileName string The entity  photoFileName field
     * @param   $defalutLanguage string The entity  defalutLanguage field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewUserProfile($userId, $photoFileName, $defalutLanguage) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewUserProfile($userId, $photoFileName, $defalutLanguage);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates UserProfile item
     * @param  $profileId int The entity  profileId field 
     * @param  $userId int The entity  userId field 
     * @param  $photoFileName string The entity  photoFileName field 
     * @param  $defalutLanguage string The entity  defalutLanguage field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateUserProfile($profileId, $userId, $photoFileName, $defalutLanguage) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserProfile($profileId, $userId, $photoFileName, $defalutLanguage);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates UserProfile item  details

     * @param  $profileId int The entity  profileId field 
     * @param  $userId int The entity  userId field 
     * @param  $photoFileName string The entity  photoFileName field 
     * @param  $defalutLanguage string The entity  defalutLanguage field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserProfileDetails($profileId, $userId, $photoFileName, $defalutLanguage) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserProfileDetails($profileId, $userId, $photoFileName, $defalutLanguage);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates userId of the UserProfile entity
     * @param   $profileId int The entity  profileId field 
     * @param   $userId int The entity  userId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserProfileUserId($profileId, $userId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserProfileUserId($profileId, $userId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates photoFileName of the UserProfile entity
     * @param   $profileId int The entity  profileId field 
     * @param   $photoFileName string The entity  photoFileName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserProfilePhotoFileName($profileId, $photoFileName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserProfilePhotoFileName($profileId, $photoFileName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates defalutLanguage of the UserProfile entity
     * @param   $profileId int The entity  profileId field 
     * @param   $defalutLanguage string The entity  defalutLanguage field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserProfileDefalutLanguage($profileId, $defalutLanguage) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserProfileDefalutLanguage($profileId, $defalutLanguage);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the UserProfile item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserProfileEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "userId":
                    return $this->updateUserProfileUserId($keyFieldValue, $newFieldValue);

                case "photoFileName":
                    return $this->updateUserProfilePhotoFileName($keyFieldValue, $newFieldValue);

                case "defalutLanguage":
                    return $this->updateUserProfileDefalutLanguage($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes UserProfile item
     * @param  $profileId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteUserProfile($profileId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteUserProfile($profileId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected UserProfile items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedUserProfiles($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteUserProfile($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete UserProfile !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all UserProfile items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllUserProfiles() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllUserProfiles();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
