
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The User model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class User {

    private $userId;
    private $gender;
    private $loginName;
    private $hashPassword;
    private $name;
    private $lastName;
    private $phoneNumber;
    private $email;
    private $zipCode;
    private $city;
    private $address;

    /** Constructor of an User object
     *  @param $userId int The entity  primary key field 
     * @param  $gender string The entity  gender field 
     * @param  $loginName string The entity  loginName field 
     * @param  $hashPassword string The entity  hashPassword field 
     * @param  $name string The entity  name field 
     * @param  $lastName string The entity  lastName field 
     * @param  $phoneNumber string The entity  phoneNumber field 
     * @param  $email string The entity  email field 
     * @param  $zipCode string The entity  zipCode field 
     * @param  $city string The entity  city field 
     * @param  $address string The entity  address field 
     */
    function __construct($userId = "", $gender = "", $loginName = "", $hashPassword = "", $name = "", $lastName = "", $phoneNumber = "", $email = "", $zipCode = "", $city = "", $address = "") {
        $this->userId = $userId;
        $this->gender = $gender;
        $this->loginName = $loginName;
        $this->hashPassword = $hashPassword;
        $this->name = $name;
        $this->lastName = $lastName;
        $this->phoneNumber = $phoneNumber;
        $this->email = $email;
        $this->zipCode = $zipCode;
        $this->city = $city;
        $this->address = $address;
    }

    /**
     * Gets  $gender value
     * @param $gender
     * @return mixed
     */
    public function getGender() {
        return $this->gender;
    }

    /**
     * Gets  $loginName value
     * @param $loginName
     * @return mixed
     */
    public function getLoginName() {
        return $this->loginName;
    }

    /**
     * Gets  $hashPassword value
     * @param $hashPassword
     * @return mixed
     */
    public function getHashPassword() {
        return $this->hashPassword;
    }

    /**
     * Gets  $name value
     * @param $name
     * @return mixed
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Gets  $lastName value
     * @param $lastName
     * @return mixed
     */
    public function getLastName() {
        return $this->lastName;
    }

    /**
     * Gets  $phoneNumber value
     * @param $phoneNumber
     * @return mixed
     */
    public function getPhoneNumber() {
        return $this->phoneNumber;
    }

    /**
     * Gets  $email value
     * @param $email
     * @return mixed
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Gets  $zipCode value
     * @param $zipCode
     * @return mixed
     */
    public function getZipCode() {
        return $this->zipCode;
    }

    /**
     * Gets  $city value
     * @param $city
     * @return mixed
     */
    public function getCity() {
        return $this->city;
    }

    /**
     * Gets  $address value
     * @param $address
     * @return mixed
     */
    public function getAddress() {
        return $this->address;
    }

    /**
     * Sets  $gender value
     * @param $gender
     * @return void
     */
    public function setGender($gender) {
        $this->gender = $gender;
    }

    /**
     * Sets  $loginName value
     * @param $loginName
     * @return void
     */
    public function setLoginName($loginName) {
        $this->loginName = $loginName;
    }

    /**
     * Sets  $hashPassword value
     * @param $hashPassword
     * @return void
     */
    public function setHashPassword($hashPassword) {
        $this->hashPassword = $hashPassword;
    }

    /**
     * Sets  $name value
     * @param $name
     * @return void
     */
    public function setName($name) {
        $this->name = $name;
    }

    /**
     * Sets  $lastName value
     * @param $lastName
     * @return void
     */
    public function setLastName($lastName) {
        $this->lastName = $lastName;
    }

    /**
     * Sets  $phoneNumber value
     * @param $phoneNumber
     * @return void
     */
    public function setPhoneNumber($phoneNumber) {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Sets  $email value
     * @param $email
     * @return void
     */
    public function setEmail($email) {
        $this->email = $email;
    }

    /**
     * Sets  $zipCode value
     * @param $zipCode
     * @return void
     */
    public function setZipCode($zipCode) {
        $this->zipCode = $zipCode;
    }

    /**
     * Sets  $city value
     * @param $city
     * @return void
     */
    public function setCity($city) {
        $this->city = $city;
    }

    /**
     * Sets  $address value
     * @param $address
     * @return void
     */
    public function setAddress($address) {
        $this->address = $address;
    }

    /**
     * Selects all User items
     * @return
     *   array The object having all User items
     *    or string with the Exception details if error occured
     */
    public function selectAllUsers() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllUsers();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets User item
     * @param $userId int  The table primary key
     * @return
     *   array The object with the given $userId value
     */
    public function getUserDetails($userId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectUserDetails($userId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new User entity
     * @param  $gender string The entity  gender field 
     * @param   $loginName string The entity  loginName field
     * @param   $hashPassword string The entity  hashPassword field
     * @param   $name string The entity  name field
     * @param   $lastName string The entity  lastName field
     * @param   $phoneNumber string The entity  phoneNumber field
     * @param   $email string The entity  email field
     * @param   $zipCode string The entity  zipCode field
     * @param   $city string The entity  city field
     * @param   $address string The entity  address field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewUser($gender, $loginName, $hashPassword, $name, $lastName, $phoneNumber, $email, $zipCode, $city, $address) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewUser($gender, $loginName, $hashPassword, $name, $lastName, $phoneNumber, $email, $zipCode, $city, $address);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates User item
     * @param  $userId int The entity  userId field 
     * @param  $gender string The entity  gender field 
     * @param  $loginName string The entity  loginName field 
     * @param  $hashPassword string The entity  hashPassword field 
     * @param  $name string The entity  name field 
     * @param  $lastName string The entity  lastName field 
     * @param  $phoneNumber string The entity  phoneNumber field 
     * @param  $email string The entity  email field 
     * @param  $zipCode string The entity  zipCode field 
     * @param  $city string The entity  city field 
     * @param  $address string The entity  address field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateUser($userId, $gender, $loginName, $hashPassword, $name, $lastName, $phoneNumber, $email, $zipCode, $city, $address) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUser($userId, $gender, $loginName, $hashPassword, $name, $lastName, $phoneNumber, $email, $zipCode, $city, $address);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates User item  details

     * @param  $userId int The entity  userId field 
     * @param  $gender string The entity  gender field 
     * @param  $loginName string The entity  loginName field 
     * @param  $hashPassword string The entity  hashPassword field 
     * @param  $name string The entity  name field 
     * @param  $lastName string The entity  lastName field 
     * @param  $phoneNumber string The entity  phoneNumber field 
     * @param  $email string The entity  email field 
     * @param  $zipCode string The entity  zipCode field 
     * @param  $city string The entity  city field 
     * @param  $address string The entity  address field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserDetails($userId, $gender, $loginName, $hashPassword, $name, $lastName, $phoneNumber, $email, $zipCode, $city, $address) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserDetails($userId, $gender, $loginName, $hashPassword, $name, $lastName, $phoneNumber, $email, $zipCode, $city, $address);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates gender of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $gender string The entity  gender field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserGender($userId, $gender) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserGender($userId, $gender);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates loginName of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $loginName string The entity  loginName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserLoginName($userId, $loginName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserLoginName($userId, $loginName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates hashPassword of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $hashPassword string The entity  hashPassword field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserHashPassword($userId, $hashPassword) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserHashPassword($userId, $hashPassword);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates name of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $name string The entity  name field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserName($userId, $name) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserName($userId, $name);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates lastName of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $lastName string The entity  lastName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserLastName($userId, $lastName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserLastName($userId, $lastName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates phoneNumber of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $phoneNumber string The entity  phoneNumber field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserPhoneNumber($userId, $phoneNumber) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserPhoneNumber($userId, $phoneNumber);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates email of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $email string The entity  email field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserEmail($userId, $email) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserEmail($userId, $email);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates zipCode of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $zipCode string The entity  zipCode field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserZipCode($userId, $zipCode) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserZipCode($userId, $zipCode);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates city of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $city string The entity  city field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserCity($userId, $city) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserCity($userId, $city);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates address of the User entity
     * @param   $userId int The entity  userId field 
     * @param   $address string The entity  address field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserAddress($userId, $address) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateUserAddress($userId, $address);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the User item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateUserEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "gender":
                    return $this->updateUserGender($keyFieldValue, $newFieldValue);

                case "loginName":
                    return $this->updateUserLoginName($keyFieldValue, $newFieldValue);

                case "hashPassword":
                    return $this->updateUserHashPassword($keyFieldValue, $newFieldValue);

                case "name":
                    return $this->updateUserName($keyFieldValue, $newFieldValue);

                case "lastName":
                    return $this->updateUserLastName($keyFieldValue, $newFieldValue);

                case "phoneNumber":
                    return $this->updateUserPhoneNumber($keyFieldValue, $newFieldValue);

                case "email":
                    return $this->updateUserEmail($keyFieldValue, $newFieldValue);

                case "zipCode":
                    return $this->updateUserZipCode($keyFieldValue, $newFieldValue);

                case "city":
                    return $this->updateUserCity($keyFieldValue, $newFieldValue);

                case "address":
                    return $this->updateUserAddress($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes User item
     * @param  $userId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteUser($userId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteUser($userId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected User items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedUsers($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteUser($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete User !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all User items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllUsers() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllUsers();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Custom added User methods
     */

    /**
     * Checks user login data for Authentication
     * @param
     *   $userLoginName string  The user login name
     *   $userPassword string  The user password
     * @return boolean
     */
    public function checkUserLoginData($userLoginName, $userPassword) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->checkUserLoginData($userLoginName, $userPassword);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets logged User credentials
     * @param
     * $userLoginName string The user login name
     * @return mixed
     */
    public function getUserCredentialsData($userLoginName) {
        $allUsers = $this->selectAllUsers();
        $userData = array();
        for ($i = 0; $i < count($allUsers); $i++) {
            if ($allUsers[$i]["loginName"] == $userLoginName) {
                array_push($userData, array("loginName" => $allUsers[$i]["loginName"]  
                    ,"userId" => $allUsers[$i]["userId"]
                    ,"name" => $allUsers[$i]["name"]
                    ,"lastName" => $allUsers[$i]["lastName"]
                    ,"phoneNumber" => $allUsers[$i]["phoneNumber"]
                    ,"email" => $allUsers[$i]["email"]
                ));
                //array_push($userData, array("hashPassword" => Utils::hashString($allUsers[$i]["hashPassword"])));
                
                return $userData;
            }
        }
        return $userData;
    }

}
