
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The Veteran model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class Veteran {

    private $veteranId;
    private $gender;
    private $name;
    private $lastName;
    private $email;
    private $phoneNumber;
    private $zipCode;
    private $city;
    private $address;
    private $position;

    /** Constructor of an Veteran object
     *  @param $veteranId int The entity  primary key field 
     * @param  $gender string The entity  gender field 
     * @param  $name string The entity  name field 
     * @param  $lastName string The entity  lastName field 
     * @param  $email string The entity  email field 
     * @param  $phoneNumber string The entity  phoneNumber field 
     * @param  $zipCode string The entity  zipCode field 
     * @param  $city string The entity  city field 
     * @param  $address string The entity  address field 
     * @param  $position string The entity  position field 
     */
    function __construct($veteranId = "", $gender = "", $name = "", $lastName = "", $email = "", $phoneNumber = "", $zipCode = "", $city = "", $address = "", $position = "") {
        $this->veteranId = $veteranId;
        $this->gender = $gender;
        $this->name = $name;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->phoneNumber = $phoneNumber;
        $this->zipCode = $zipCode;
        $this->city = $city;
        $this->address = $address;
        $this->position = $position;
    }

    /**
     * Gets  $gender value
     * @param $gender
     * @return mixed
     */
    public function getGender() {
        return $this->gender;
    }

    /**
     * Gets  $name value
     * @param $name
     * @return mixed
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Gets  $lastName value
     * @param $lastName
     * @return mixed
     */
    public function getLastName() {
        return $this->lastName;
    }

    /**
     * Gets  $email value
     * @param $email
     * @return mixed
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Gets  $phoneNumber value
     * @param $phoneNumber
     * @return mixed
     */
    public function getPhoneNumber() {
        return $this->phoneNumber;
    }

    /**
     * Gets  $zipCode value
     * @param $zipCode
     * @return mixed
     */
    public function getZipCode() {
        return $this->zipCode;
    }

    /**
     * Gets  $city value
     * @param $city
     * @return mixed
     */
    public function getCity() {
        return $this->city;
    }

    /**
     * Gets  $address value
     * @param $address
     * @return mixed
     */
    public function getAddress() {
        return $this->address;
    }

    /**
     * Gets  $position value
     * @param $position
     * @return mixed
     */
    public function getPosition() {
        return $this->position;
    }

    /**
     * Sets  $gender value
     * @param $gender
     * @return void
     */
    public function setGender($gender) {
        $this->gender = $gender;
    }

    /**
     * Sets  $name value
     * @param $name
     * @return void
     */
    public function setName($name) {
        $this->name = $name;
    }

    /**
     * Sets  $lastName value
     * @param $lastName
     * @return void
     */
    public function setLastName($lastName) {
        $this->lastName = $lastName;
    }

    /**
     * Sets  $email value
     * @param $email
     * @return void
     */
    public function setEmail($email) {
        $this->email = $email;
    }

    /**
     * Sets  $phoneNumber value
     * @param $phoneNumber
     * @return void
     */
    public function setPhoneNumber($phoneNumber) {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Sets  $zipCode value
     * @param $zipCode
     * @return void
     */
    public function setZipCode($zipCode) {
        $this->zipCode = $zipCode;
    }

    /**
     * Sets  $city value
     * @param $city
     * @return void
     */
    public function setCity($city) {
        $this->city = $city;
    }

    /**
     * Sets  $address value
     * @param $address
     * @return void
     */
    public function setAddress($address) {
        $this->address = $address;
    }

    /**
     * Sets  $position value
     * @param $position
     * @return void
     */
    public function setPosition($position) {
        $this->position = $position;
    }

    /**
     * Selects all Veteran items
     * @return
     *   array The object having all Veteran items
     *    or string with the Exception details if error occured
     */
    public function selectAllVeterans() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllVeterans();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets Veteran item
     * @param $veteranId int  The table primary key
     * @return
     *   array The object with the given $veteranId value
     */
    public function getVeteranDetails($veteranId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectVeteranDetails($veteranId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new Veteran entity
     * @param  $gender string The entity  gender field 
     * @param   $name string The entity  name field
     * @param   $lastName string The entity  lastName field
     * @param   $email string The entity  email field
     * @param   $phoneNumber string The entity  phoneNumber field
     * @param   $zipCode string The entity  zipCode field
     * @param   $city string The entity  city field
     * @param   $address string The entity  address field
     * @param   $position string The entity  position field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewVeteran($gender, $name, $lastName, $email, $phoneNumber, $zipCode, $city, $address, $position) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewVeteran($gender, $name, $lastName, $email, $phoneNumber, $zipCode, $city, $address, $position);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Veteran item
     * @param  $veteranId int The entity  veteranId field 
     * @param  $gender string The entity  gender field 
     * @param  $name string The entity  name field 
     * @param  $lastName string The entity  lastName field 
     * @param  $email string The entity  email field 
     * @param  $phoneNumber string The entity  phoneNumber field 
     * @param  $zipCode string The entity  zipCode field 
     * @param  $city string The entity  city field 
     * @param  $address string The entity  address field 
     * @param  $position string The entity  position field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateVeteran($veteranId, $gender, $name, $lastName, $email, $phoneNumber, $zipCode, $city, $address, $position) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteran($veteranId, $gender, $name, $lastName, $email, $phoneNumber, $zipCode, $city, $address, $position);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates Veteran item  details

     * @param  $veteranId int The entity  veteranId field 
     * @param  $gender string The entity  gender field 
     * @param  $name string The entity  name field 
     * @param  $lastName string The entity  lastName field 
     * @param  $email string The entity  email field 
     * @param  $phoneNumber string The entity  phoneNumber field 
     * @param  $zipCode string The entity  zipCode field 
     * @param  $city string The entity  city field 
     * @param  $address string The entity  address field 
     * @param  $position string The entity  position field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranDetails($veteranId, $gender, $name, $lastName, $email, $phoneNumber, $zipCode, $city, $address, $position) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranDetails($veteranId, $gender, $name, $lastName, $email, $phoneNumber, $zipCode, $city, $address, $position);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates gender of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $gender string The entity  gender field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranGender($veteranId, $gender) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranGender($veteranId, $gender);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates name of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $name string The entity  name field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranName($veteranId, $name) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranName($veteranId, $name);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates lastName of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $lastName string The entity  lastName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranLastName($veteranId, $lastName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranLastName($veteranId, $lastName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates email of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $email string The entity  email field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranEmail($veteranId, $email) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranEmail($veteranId, $email);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates phoneNumber of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $phoneNumber string The entity  phoneNumber field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranPhoneNumber($veteranId, $phoneNumber) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranPhoneNumber($veteranId, $phoneNumber);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates zipCode of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $zipCode string The entity  zipCode field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranZipCode($veteranId, $zipCode) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranZipCode($veteranId, $zipCode);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates city of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $city string The entity  city field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranCity($veteranId, $city) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranCity($veteranId, $city);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates address of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $address string The entity  address field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranAddress($veteranId, $address) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranAddress($veteranId, $address);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates position of the Veteran entity
     * @param   $veteranId int The entity  veteranId field 
     * @param   $position string The entity  position field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranPosition($veteranId, $position) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateVeteranPosition($veteranId, $position);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the Veteran item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateVeteranEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "gender":
                    return $this->updateVeteranGender($keyFieldValue, $newFieldValue);

                case "name":
                    return $this->updateVeteranName($keyFieldValue, $newFieldValue);

                case "lastName":
                    return $this->updateVeteranLastName($keyFieldValue, $newFieldValue);

                case "email":
                    return $this->updateVeteranEmail($keyFieldValue, $newFieldValue);

                case "phoneNumber":
                    return $this->updateVeteranPhoneNumber($keyFieldValue, $newFieldValue);

                case "zipCode":
                    return $this->updateVeteranZipCode($keyFieldValue, $newFieldValue);

                case "city":
                    return $this->updateVeteranCity($keyFieldValue, $newFieldValue);

                case "address":
                    return $this->updateVeteranAddress($keyFieldValue, $newFieldValue);

                case "position":
                    return $this->updateVeteranPosition($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes Veteran item
     * @param  $veteranId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteVeteran($veteranId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteVeteran($veteranId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected Veteran items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedVeterans($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteVeteran($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete Veteran !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all Veteran items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllVeterans() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllVeterans();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
